musics = [
  ["Arcadia", "arcadia.png"],
  ["Celestial Future", "celestial_future.png"],
  ["KING", "king.png"],
  ["WARRIOR", "warrior.png"],
  ["アイドル", "idol.png"],
  ["あなたしかいないから", "anata_shika_inai_kara.png"],
  ["エゴロック", "ego_rock.png"],
  ["おこめごころ", "okomegokoro.png"],
  ["輝石のDESTINATION feat. 花たん", "kiseki_no_destination_feat._hanatan.png"],
  ["強風オールバック", "kyoufuu_all_back.png"],
  ["月下美人", "gekkabijin.png"],
  ["さよならストローク", "sayonara_stroke.png"],
  ["惨事のヒロイン、朝を待つ。", "sanji_no_heroine,_asa_wo_matsu..png"],
  ["シューティンスター★☆", "shooting_star.png"],
  ["青春コンプレックス", "seishun_complex.png"],
  ["打打打打打打打打打打", "dadadadadadadadadada.png"],
  ["虹の先に何があるか - Remaster -", "niji_no_saki_ni_nani_ga_aru_ka.png"],
  ["愛はToxic! feat.LilyMone", "ai_wa_toxic_feat_lilymone.png"],
  ["Astrum", "astrum.png"],
  ["Calm days", "calm_days.png"],
  ["DESPERATE ERROR", "desperate_error.png"],
  ["Far East Nightbird (GITADORA Remix)", "far_east_nightbird_gitadora_remix.png"],
  ["ABSOLUTE R6", "absolute_r6.png"],
];
