musics = [
  ["47", "Across the nightmare", "ACROSSTHENIGHTMARE", "Jimmy Weckl", "JIMMYWECKL", "GF2&DM1", "0"],
  ["48", "Cutie pie", "CUTIEPIE", "Toshio Sakurai", "TOSHIOSAKURAI", "GF1", "0"],
  ["49", "FIRE", "FIRE", "泉 陸奥彦", "いずみむつひこ", "GF1", "0"],
  ["50", "Happy man", "HAPPYMAN", "泉 陸奥彦", "いずみむつひこ", "GF1", "0"],
  ["51", "Heaven is a '57 metallic gray", "HEAVENISA57METALLICGRAY", "Sweet little 30's", "SWEETLITTLE30S", "GF2&DM1", "0"],
  ["52", "Hypnotica", "HYPNOTICA", "Naoki Maeda", "NAOKIMAEDA", "GF1", "0"],
  ["53", "I think about you", "ITHINKABOUTYOU", "Elizabeth Dobbs", "ELIZABETHDOBBS", "GF2&DM1", "0"],
  ["54", "JET WORLD", "JETWORLD", "泉 陸奥彦", "いずみむつひこ", "GF2&DM1", "0"],
  ["55", "LUCKY? STAFF", "LUCKYSTAFF", "泉 陸奥彦", "いずみむつひこ", "GF1", "0"],
  ["56", "PRIMAL SOUL", "PRIMALSOUL", "泉 陸奥彦", "いずみむつひこ", "GF2&DM1", "0"],
  ["57", "Ska Ska No.1", "SKASKANO1", "小野秀幸", "おのひでゆき", "GF2&DM1", "0"],
  ["59", "BREAK OUT", "BREAKOUT", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF3&DM2", "0"],
  ["60", "CLASSIC PARTY", "CLASSICPARTY", "小野秀幸", "おのひでゆき", "GF3&DM2", "0"],
  ["61", "COSMIC COWGIRL", "COSMICCOWGIRL", "Toshio Sakurai", "TOSHIOSAKURAI", "GF3&DM2", "0"],
  ["62", "LOUD!", "LOUD", "泉 陸奥彦", "いずみむつひこ", "GF3&DM2", "0"],
  ["63", "MIDNIGHT SPECIAL", "MIDNIGHTSPECIAL", "Love machineguns", "LOVEMACHINEGUNS", "GF3&DM2", "0"],
  ["64", "P.P.R.", "PPR", "Handsome JET", "HANDSOMEJET", "GF3&DM2", "0"],
  ["65", "SAY WHAT YOU MEAN", "SAYWHATYOUMEAN", "Monaural Heads*1", "MONAURALHEADS1", "GF3&DM2", "0"],
  ["66", "STOP SPINNING ME IN CIRCLES", "STOPSPINNINGMEINCIRCLES", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF3&DM2", "0"],
  ["68", "CAPTAIN'S VOYAGE", "CAPTAINSVOYAGE", "古川もとあき", "ふるかわもとあき", "GF4&DM3", "0"],
  ["69", "CARNIVAL DAY", "CARNIVALDAY", "Paula Terry & Fu Fu's", "PAULATERRYFUFUS", "GF4&DM3", "0"],
  ["70", "CLASSIC PARTY 2", "CLASSICPARTY2", "小野秀幸", "おのひでゆき", "GF4&DM3", "0"],
  ["71", "DAY DREAM", "DAYDREAM", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF4&DM3", "0"],
  ["72", "GIANT SLUG", "GIANTSLUG", "Aaron G", "AARONG", "GF4&DM3", "0"],
  ["73", "I'M GONNA GET YOU!", "IMGONNAGETYOU", "Kelly Cosmo", "KELLYCOSMO", "GF4&DM3", "0"],
  ["74", "RIGHT ON TIME", "RIGHTONTIME", "Robbie Danzie", "ROBBIEDANZIE", "GF4&DM3", "0"],
  ["75", "SEA ANEMONES", "SEAANEMONES", "Jimmy Weckl", "JIMMYWECKL", "GF4&DM3", "0"],
  ["77", "CASSANDRA", "CASSANDRA", "亜熱帯マジ-SKA爆弾", "あねったいまじSKAばくだん", "GF5&DM4", "0"],
  ["78", "CLASSIC PARTY 3", "CLASSICPARTY3", "小野秀幸", "おのひでゆき", "GF5&DM4", "0"],
  ["79", "FIRE IN THE DARK", "FIREINTHEDARK", "Kevin Vecchione", "KEVINVECCHIONE", "GF5&DM4", "0"],
  ["80", "THREE WORMS", "THREEWORMS", "Jimmy Weckl", "JIMMYWECKL", "GF5&DM4", "0"],
  ["81", "TIGER, TOO", "TIGERTOO", "Stephen Mcknight", "STEPHENMCKNIGHT", "GF5&DM4", "0"],
  ["82", "The Least 100sec", "THELEAST100SEC", "佐々木博史", "ささきひろし", "GF5&DM4", "0"],
  ["83", "VOIDDD", "VOIDDD", "Des-ROW feat.Kevin Vecchione", "DESROWFEATKEVINVECCHIONE", "GF5&DM4", "0"],
  ["84", "ありがとね。", "ありがとね", "MAKI", "MAKI", "GF5&DM4", "0"],
  ["86", "BLIND", "BLIND", "有待雅彦", "ありまちまさひこ", "GF6&DM5", "0"],
  ["87", "BOBBY SUE AND SKINNY JIM", "BOBBYSUEANDSKINNYJIM", "Raj Ramayya", "RAJRAMAYYA", "GF6&DM5", "0"],
  ["88", "Brazilian Anthem", "BRAZILIANANTHEM", "Berimbau '66", "BERIMBAU66", "GF6&DM5", "0"],
  ["89", "E-MAIL ME!", "EMAILME", "Paula Terry", "PAULATERRY", "GF6&DM5", "0"],
  ["90", "FEEL THE EARTH", "FEELTHEEARTH", "古川もとあき", "ふるかわもとあき", "GF6&DM5", "0"],
  ["91", "FIREBALL", "FIREBALL", "Sweet little 30's", "SWEETLITTLE30S", "GF6&DM5", "0"],
  ["92", "Herring roe", "HERRINGROE", "Jimmy Weckl", "JIMMYWECKL", "GF6&DM5", "0"],
  ["93", "MIDNIGHT SUN", "MIDNIGHTSUN", "泉 陸奥彦", "いずみむつひこ", "GF6&DM5", "0"],
  ["94", "STOP THIS TRAIN", "STOPTHISTRAIN", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF6&DM5", "0"],
  ["95", "Sunflower Girl", "SUNFLOWERGIRL", "SHORTCUTS", "SHORTCUTS", "GF6&DM5", "0"],
  ["96", "Yellow Panic Time", "YELLOWPANICTIME", "肥塚良彦", "こえづかよしひこ", "GF6&DM5", "0"],
  ["97", "hypnotheque", "HYPNOTHEQUE", "NM", "NM", "GF6&DM5", "0"],
  ["98", "plastic imitations", "PLASTICIMITATIONS", "Kevin Vecchione", "KEVINVECCHIONE", "GF6&DM5", "0"],
  ["99", "君のとなりに・・・", "きみのとなりに", "Handsome JET Project", "HANDSOMEJETPROJECT", "GF6&DM5", "0"],
  ["100", "子供の落書き帳", "こどものらくがきちょう", "佐々木博史", "ささきひろし", "GF6&DM5", "0"],
  ["101", "正論", "せいろん", "鈴木愛", "すずきあい", "GF6&DM5", "0"],
  ["103", "Concertino in Blue", "CONCERTINOINBLUE", "佐々木博史", "ささきひろし", "GF7&DM6", "0"],
  ["104", "Destiny lovers", "DESTINYLOVERS", "くにたけ みゆき", "くにたけみゆき", "GF7&DM6", "0"],
  ["105", "GETAWAY", "GETAWAY", "浦田隆志・平田久美子", "うらたたかしひらたくみこ", "GF7&DM6", "0"],
  ["106", "MODEL DD2", "MODELDD2", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF7&DM6", "0"],
  ["107", "Moonlight Walkin'", "MOONLIGHTWALKIN", "入尾信充 with Yah Yah's", "いりおのぶみつWITHYAHYAHS", "GF7&DM6", "0"],
  ["108", "O JIYA", "OJIYA", "ASMAT & emi", "ASMATEMI", "GF7&DM6", "0"],
  ["109", "One Phrase Blues", "ONEPHRASEBLUES", "小野秀幸", "おのひでゆき", "GF7&DM6", "0"],
  ["110", "ROCKIN' PARADISE", "ROCKINPARADISE", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF7&DM6", "0"],
  ["111", "Rebirth", "REBIRTH", "MAKI", "MAKI", "GF7&DM6", "0"],
  ["112", "SMILE FOR YOU", "SMILEFORYOU", "古川もとあき", "ふるかわもとあき", "GF7&DM6", "0"],
  ["113", "WILD RIDE", "WILDRIDE", "中村康三", "なかむらこうぞう", "GF7&DM6", "0"],
  ["114", "innocent world", "INNOCENTWORLD", "", "", "GF7&DM6,有名楽曲", "0"],
  ["115", "jet coaster☆girl", "JETCOASTERGIRL", "TOMOSUKE feat. Three Berry Icecream", "TOMOSUKEFEATTHREEBERRYICECREAM", "GF7&DM6", "0"],
  ["116", "under control", "UNDERCONTROL", "Kevin Vecchione", "KEVINVECCHIONE", "GF7&DM6", "0"],
  ["117", "すてきな雨あがり", "すてきなあめあがり", "寺島純子", "てらしまじゅんこ", "GF7&DM6", "0"],
  ["118", "スイマーズ", "すいまーず", "亜熱帯マジ-SKA爆弾 feat. MAKI", "あねったいまじSKAばくだんFEATMAKI", "GF7&DM6", "0"],
  ["119", "蛹", "さなぎ", "あさき", "あさき", "GF7&DM6", "0"],
  ["120", "誰?", "だれ", "Handsome JET Project", "HANDSOMEJETPROJECT", "GF7&DM6", "0"],
  ["122", "BRE∀K DOWN! (GF&DM STYLE)", "BREKDOWNGFDMSTYLE", "BeForU", "BEFORU", "GF8&DM7", "0"],
  ["123", "CHOCOLATE PHILOSOPHY", "CHOCOLATEPHILOSOPHY", "常盤ゆう", "ときわゆう", "GF8&DM7", "0"],
  ["124", "Homesick Pt.2&3", "HOMESICKPT23", "ORANGENOISE SHORTCUT", "ORANGENOISESHORTCUT", "GF8&DM7", "0"],
  ["125", "Infinite", "INFINITE", "PARALLEL FLOATERS", "PARALLELFLOATERS", "GF8&DM7", "0"],
  ["126", "KISS ME GOODBYE!", "KISSMEGOODBYE", "TAEKO", "TAEKO", "GF8&DM7", "0"],
  ["127", "Keiko my love", "KEIKOMYLOVE", "Jimmy Weckl", "JIMMYWECKL", "GF8&DM7", "0"],
  ["128", "MODEL DD3", "MODELDD3", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF8&DM7", "0"],
  ["129", "THE OCEAN AND YOU", "THEOCEANANDYOU", "古川もとあき", "ふるかわもとあき", "GF8&DM7", "0"],
  ["130", "To the IST", "TOTHEIST", "Glancer", "GLANCER", "GF8&DM7", "0"],
  ["131", "begin", "BEGIN", "小坂りゆ", "こさかりゆ", "GF8&DM7", "0"],
  ["132", "cachaca", "CACHACA", "Mokky de Yah Yah's", "MOKKYDEYAHYAHS", "GF8&DM7", "0"],
  ["133", "too late two", "TOOLATETWO", "Des-ROW", "DESROW", "GF8&DM7", "0"],
  ["134", "そっと。", "そっと", "鈴木愛", "すずきあい", "GF8&DM7", "0"],
  ["135", "たまゆら", "たまゆら", "佐々木博史", "ささきひろし", "GF8&DM7", "0"],
  ["136", "わすれもの", "わすれもの", "Handsome JET Project feat.mizushina", "HANDSOMEJETPROJECTFEATMIZUSHINA", "GF8&DM7", "0"],
  ["137", "スタアの恋人", "すたあのこいびと", "くにたけ みゆき", "くにたけみゆき", "GF8&DM7", "0"],
  ["138", "ツミナガラ... と彼女は謂ふ", "みつながらとかのじょはいふ", "あさき", "あさき", "GF8&DM7", "0"],
  ["139", "三毛猫ロック", "みけねころっく", "亜熱帯マジ-SKA爆弾", "あねったいまじSKAばくだん", "GF8&DM7", "0"],
  ["140", "人にやさしく", "ひとにやさしく", "", "", "GF8&DM7,有名楽曲", "0"],
  ["141", "美麗的家郷", "めいりーでじあしゃん", "劉 鋒", "りゅうほう", "GF8&DM7", "0"],
  ["143", "777", "777", "EeL", "EEL", "GF9&DM8", "0"],
  ["144", "Black horizon", "BLACKHORIZON", "Trick Trap", "TRICKTRAP", "GF9&DM8", "0"],
  ["145", "Country day", "COUNTRYDAY", "Anna Vieste", "ANNAVIESTE", "GF9&DM8", "0"],
  ["146", "DIAMONDS", "DIAMONDS", "", "", "GF9&DM8,有名楽曲", "0"],
  ["147", "GET READY", "GETREADY", "古川もとあき", "ふるかわもとあき", "GF9&DM8", "0"],
  ["148", "I'm a loser", "IMALOSER", "樽木栄一郎", "たるきえいいちろう", "GF9&DM8", "0"],
  ["149", "MAD BLAST", "MADBLAST", "THE INFECTION", "THEINFECTION", "GF9&DM8", "0"],
  ["150", "MODEL DD4", "MODELDD4", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF9&DM8", "0"],
  ["151", "S.P.I.P.", "SPIP", "Thomas' Family with Yah Yah's", "THOMASFAMILYWITHYAHYAHS", "GF9&DM8", "0"],
  ["152", "TIERRA BUENA", "TIERRABUENA", "WILMA DE OLIVEIRA", "WILMADEOLIVEIRA", "GF9&DM8", "0"],
  ["153", "Utopia", "UTOPIA", "寺島純子", "てらしまじゅんこ", "GF9&DM8", "0"],
  ["154", "チカラ", "ちから", "BeForU", "BEFORU", "GF9&DM8", "0"],
  ["155", "万華鏡", "まんげきょう", "Jimmy Weckl", "JIMMYWECKL", "GF9&DM8", "0"],
  ["156", "大見解", "だいけんかい", "Des-ROW・組", "DESROWぐみ", "GF9&DM8", "0"],
  ["157", "月光蝶", "げっこうちょう", "あさき", "あさき", "GF9&DM8", "0"],
  ["158", "林檎と蜂蜜", "りんごとはちみつ", "亜熱帯マジ-SKA爆弾 feat. MAKI", "あねったいまじSKAばくだんFEATMAKI", "GF9&DM8", "0"],
  ["159", "涙のregret", "なみだのregret", "くにたけ みゆき", "くにたけみゆき", "GF9&DM8", "0"],
  ["160", "花の唄", "はなのうた", "ちーちゃん", "ちーちゃん", "GF9&DM8", "0"],
  ["162", "Agnus Dei", "AGNUSDEI", "あさき", "あさき", "GF10&DM9", "0"],
  ["163", "Funky sonic World", "FUNKYSONICWORLD", "Des-ROW feat.SHIGE", "DESROWFEATSHIGE", "GF10&DM9", "0"],
  ["164", "GET IT ALL", "GETITALL", "BRASS TRICKS", "BRASSTRICKS", "GF10&DM9", "0"],
  ["165", "Libra", "LIBRA", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF10&DM9", "0"],
  ["166", "MODEL DD5", "MODELDD5", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF10&DM9", "0"],
  ["167", "RISE", "RISE", "泉 陸奥彦", "いずみむつひこ", "GF10&DM9", "0"],
  ["168", "SA-DA-ME", "SADAME", "good-cool feat. すわひでお", "GOODCOOLFEATすわひでお", "GF10&DM9", "0"],
  ["169", "Timepiece phase II", "TIMEPIECEPHASEII", "佐々木博史", "ささきひろし", "GF10&DM9", "0"],
  ["170", "cockpit", "COCKPIT", "Jimmy Weckl", "JIMMYWECKL", "GF10&DM9", "0"],
  ["171", "joker", "JOKER", "Jimmy Weckl", "JIMMYWECKL", "GF10&DM9", "0"],
  ["172", "mint candy ☆ citrus drop", "MINTCANDYCITRUSDROP", "U.KI", "UKI", "GF10&DM9", "0"],
  ["173", "この子の七つのお祝いに", "このこのななつのおいわいに", "あさき", "あさき", "GF10&DM9", "0"],
  ["174", "しかられ日和", "しかられびより", "Handsome JETと亜熱帯マジ-SKA爆弾", "HANDSOMEJETとあねったいまじSKAばくだん", "GF10&DM9", "0"],
  ["175", "カゴノトリ", "かごのとり", "橙色特別室", "だいだいいろとくべつしつ", "GF10&DM9", "0"],
  ["176", "ヒマワリ", "ひまわり", "RIYU from BeForU", "RIYUFROMBEFORU", "GF10&DM9", "0"],
  ["177", "ヘリコプター", "へりこぷたー", "ピンクカプセル", "ぴんくかぷせる", "GF10&DM9", "0"],
  ["178", "大切なもの", "たいせつなもの", "", "", "GF10&DM9,有名楽曲", "0"],
  ["179", "蒼白", "そうはく", "鈴木愛", "すずきあい", "GF10&DM9", "0"],
  ["181", "Dedication", "DEDICATION", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF11&DM10", "0"],
  ["182", "Dragon Blade", "DRAGONBLADE", "Kozo Nakamura", "KOZONAKAMURA", "GF11&DM10", "0"],
  ["183", "Dream Again...", "DREAMAGAIN", "柴田浩之", "しばたひろゆき", "GF11&DM10,有名楽曲", "0"],
  ["184", "MODEL DD6", "MODELDD6", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF11&DM10", "0"],
  ["185", "MONSTER TREE", "MONSTERTREE", "", "", "GF11&DM10,有名楽曲", "0"],
  ["186", "Orbital Velocity", "ORBITALVELOCITY", "Jimmy Weckl", "JIMMYWECKL", "GF11&DM10", "0"],
  ["187", "Passion", "PASSION", "KUMIKO", "KUMIKO", "GF11&DM10", "0"],
  ["188", "Reaching for the Stars", "REACHINGFORTHESTARS", "serena", "SERENA", "GF11&DM10", "0"],
  ["189", "Real 〜Lサイズの夢〜", "REALLさいずのゆめ", "MAKI", "MAKI", "GF11&DM10", "0"],
  ["190", "Tail Spin", "TAILSPIN", "Des-ROW feat.DENNIS GUNN", "DESROWFEATDENNISGUNN", "GF11&DM10", "0"],
  ["191", "WE ARE", "WEARE", "TЁЯRA", "TERRA", "GF11&DM10", "0"],
  ["192", "YARA TUM KAHAN?", "YARATUMKAHAN", "ASMAT", "ASMAT", "GF11&DM10", "0"],
  ["193", "prism", "PRISM", "肥塚良彦", "こえづかよしひこ", "GF11&DM10", "0"],
  ["194", "☆shining☆（GF&dm style）", "SHININGGFDMSTYLE", "りゆ&のりあ", "りゆのりあ", "GF11&DM10", "0"],
  ["195", "こたつとみかん", "こたつとみかん", "ピンクカプセル", "ぴんくかぷせる", "GF11&DM10", "0"],
  ["196", "二人はラブラブ（仮）", "ふたりはらぶらぶかり", "Handsome JET Project", "HANDSOMEJETPROJECT", "GF11&DM10", "0"],
  ["197", "明鏡止水", "めいきょうしすい", "TOMOSUKE feat. あさき", "TOMOSUKEFEATあさき", "GF11&DM10", "0"],
  ["198", "青春狂騒曲", "せいしゅんきょうそうきょく", "", "", "GF11&DM10,有名楽曲", "0"],
  ["199", "鬼姫", "おにひめ", "鬼の子合唱団", "おにのこがっしょうだん", "GF11&DM10", "0"],
  ["201", "A SHOOTING STAR", "ASHOOTINGSTAR", "古川もとあき", "ふるかわもとあき", "ee' MALL 2nd avenue", "0"],
  ["202", "Aithon", "AITHON", "Kozo Nakamura", "KOZONAKAMURA", "ee' MALL 2nd avenue", "0"],
  ["203", "Marigold", "MARIGOLD", "SHORTCUTS", "SHORTCUTS", "ee' MALL 2nd avenue", "0"],
  ["204", "Wall Street down-sizer", "WALLSTREETDOWNSIZER", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "ee' MALL 2nd avenue", "0"],
  ["205", "バリバリブギ 〜涙のフルーツポンチ〜", "ばりばりぶぎなみだのふるーつぽんち", "Hedel Bendel", "HEDELBENDEL", "ee' MALL 2nd avenue", "0"],
  ["206", "ペパーミントは私の敵", "ぺぱーみんとはわたしのてき", "常盤ゆう", "ときわゆう", "ee' MALL 2nd avenue", "0"],
  ["207", "空言の海", "むなごとのそら", "音々", "ねね", "ee' MALL 2nd avenue", "0"],
  ["208", "螺子之人", "ねじのひと", "あさき", "あさき", "ee' MALL 2nd avenue", "0"],
  ["210", "AFTER A HARD DAY", "AFTERAHARDDAY", "Brad Holmes", "BRADHOLMES", "GF&DMV", "0"],
  ["211", "DOKI☆DOKI", "DOKIDOKI", "TAEKO", "TAEKO", "GF&DMV", "0"],
  ["212", "Desert Rose", "DESERTROSE", "Kozo Nakamura", "KOZONAKAMURA", "GF&DMV", "0"],
  ["213", "Die Zauberflote", "DIEZAUBERFLTE", "わんにゃん☆パニックス", "わんにゃんぱにっくす", "GF&DMV", "0"],
  ["214", "ESCAPE TO THE SKY★彡", "ESCAPETOTHESKY", "TЁЯRA", "TERRA", "GF&DMV", "0"],
  ["215", "Endless cruising", "ENDLESSCRUISING", "Des-ROW feat.SHIGE", "DESROWFEATSHIGE", "GF&DMV", "0"],
  ["216", "Fairy Tales", "FAIRYTALES", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV", "0"],
  ["217", "Flow", "FLOW", "PARALLEL FLOATERS", "PARALLELFLOATERS", "GF&DMV", "0"],
  ["218", "Gently, the rain sings for me", "GENTLYTHERAINSINGSFORME", "HOLSTEIN", "HOLSTEIN", "GF&DMV,有名楽曲", "0"],
  ["219", "HEAVEN'S COCKTAIL", "HEAVENSCOCKTAIL", "高野治幸＆NEW BIG 5", "たかのはるゆきNEWBIG5", "GF&DMV", "0"],
  ["220", "Little Prayer", "LITTLEPRAYER", "土岐麻子", "ときあさこ", "GF&DMV", "0"],
  ["221", "NO MORE CRYING", "NOMORECRYING", "Brenda Vaughn", "BRENDAVAUGHN", "GF&DMV", "0"],
  ["222", "Plastic Umbrella", "PLASTICUMBRELLA", "chico", "CHICO", "GF&DMV", "0"],
  ["223", "Say", "SAY", "TOMOKO MIWA", "TOMOKOMIWA", "GF&DMV", "0"],
  ["224", "Street Runner", "STREETRUNNER", "古川もとあき", "ふるかわもとあき", "GF&DMV", "0"],
  ["225", "White tornado", "WHITETORNADO", "Trick Trap", "TRICKTRAP", "GF&DMV", "0"],
  ["226", "You can't do it if you try", "YOUCANTDOITIFYOUTRY", "遠藤一馬&あさき", "えんどうかずまあさき", "GF&DMV", "0"],
  ["227", "ancient breeze", "ANCIENTBREEZE", "小野秀幸", "おのひでゆき", "GF&DMV", "0"],
  ["228", "going up", "GOINGUP", "colors", "COLORS", "GF&DMV", "0"],
  ["229", "mushroom boy", "MUSHROOMBOY", "Poo", "POO", "GF&DMV", "0"],
  ["230", "rebirth of love", "REBIRTHOFLOVE", "Ark of the Covenant", "ARKOFTHECOVENANT", "GF&DMV", "0"],
  ["231", "にゃんだふる55", "にゃんだふる55", "Dormir", "DORMIR", "GF&DMV", "0"],
  ["232", "ひとりぼっち", "ひとりぼっち", "ピンクカプセル", "ぴんくかぷせる", "GF&DMV", "0"],
  ["233", "タラッタダンス", "たらっただんす", "森野くま子", "もりのくまこ", "GF&DMV", "0"],
  ["234", "ルックス", "るっくす", "meli♡melo", "MELIMELO", "GF&DMV", "0"],
  ["235", "三度笠ポン太は今日も行く", "さんどがさぽんたはきょうもいく", "荒牧陽子", "あらまきようこ", "GF&DMV", "0"],
  ["236", "哀愁のコリゴリラ", "あいしゅうのこりごりら", "ハンサムジェットプロジェクト feat. みずしな孝之", "はんさむじぇっとぷろじぇくとFEATみずしなたかゆき", "GF&DMV", "0"],
  ["237", "無常の星", "むじょうのほし", "P-Bombers", "PBOMBERS", "GF&DMV", "0"],
  ["239", "Atalante", "ATALANTE", "Kozo Nakamura", "KOZONAKAMURA", "GF&DMV2", "0"],
  ["240", "CaptivAte〜裁き〜", "CAPTIVEATEさばき", "DJ YOSHITAKA feat.A/I", "DJYOSHITAKAFEATAI", "GF&DMV2", "0"],
  ["241", "GLIDE", "GLIDE", "TЁЯRA", "TERRA", "GF&DMV2", "0"],
  ["242", "Green Lime", "GREENLIME", "肥塚良彦", "こえづかよしひこ", "GF&DMV2", "0"],
  ["243", "JJ-road", "JJROAD", "JJ-road", "JJROAD", "GF&DMV2", "0"],
  ["244", "MODEL DD7", "MODELDD7", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV2", "0"],
  ["245", "Magic words ?", "MAGICWORDS", "森野くま子", "もりのくまこ", "GF&DMV2", "0"],
  ["246", "Sing A Well", "SINGAWELL", "HIGHWAY61", "HIGHWAY61", "GF&DMV2,有名楽曲", "0"],
  ["247", "Spellbound", "SPELLBOUND", "Anna Vieste", "ANNAVIESTE", "GF&DMV2", "0"],
  ["248", "Take My Hand", "TAKEMYHAND", "Maria Eva with Dream Swing Kingdom", "MARIAEVAWITHDREAMSWINGKINGDOM", "GF&DMV2", "0"],
  ["249", "Tizona d'El Cid", "TIZONADELCID", "TOMOSUKE", "TOMOSUKE", "GF&DMV2", "0"],
  ["250", "over there", "OVERTHERE", "vox", "VOX", "GF&DMV2", "0"],
  ["251", "しっぽのロック", "しっぽのろっく", "板橋ギャング", "いたばしぎゃんぐ", "GF&DMV2", "0"],
  ["252", "モラトリアム", "もらとりあむ", "MAKI", "MAKI", "GF&DMV2", "0"],
  ["253", "春の歌", "はるのうた", "", "", "GF&DMV2,有名楽曲", "0"],
  ["254", "最速逃避行", "さいそくとうひこう", "Twinkle☆berry", "TWINKLEBERRY", "GF&DMV2", "0"],
  ["255", "香港☆超特急Z", "ほんこんちょうとっきゅうZ", "明星有限公司", "みょうじょうゆうげんこうし", "GF&DMV2", "0"],
  ["257", "AXIS", "AXIS", "千本松 仁", "せんぼんまつじん", "GF&DMV3", "0"],
  ["258", "Day's!", "DAYS", "よしくんとホッシー☆", "よしくんとほっしー", "GF&DMV3", "0"],
  ["259", "El Dorado", "ELDORADO", "TAG", "TAG", "GF&DMV3", "0"],
  ["260", "Forever free", "FOREVERFREE", "colors feat.Luca", "COLORSFEATLUCA", "GF&DMV3", "0"],
  ["261", "MODEL FT2 Miracle Version", "MODELFT2MIRACLEVERSION", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV3", "0"],
  ["262", "MODEL FT2", "MODELFT2", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV3", "0"],
  ["263", "Micro fin", "MICROFIN", "Rotten Blotch", "ROTTENBLOTCH", "GF&DMV3", "0"],
  ["264", "Purple storm", "PURPLESTORM", "Trick Trap", "TRICKTRAP", "GF&DMV3", "0"],
  ["265", "Ring", "RING", "Kozo Nakamura", "KOZONAKAMURA", "GF&DMV3", "0"],
  ["266", "Ru-Ru-Ru", "RURURU", "Sis Bond Chit", "SISBONDCHIT", "GF&DMV3", "0"],
  ["267", "Venus", "VENUS", "Tatsh+RayZY", "TATSHRAYZY", "GF&DMV3", "0"],
  ["268", "ZENITH", "ZNITH", "TËЯRA", "TERRA", "GF&DMV3", "0"],
  ["269", "αρχη", "APXN", "Dormir", "DORMIR", "GF&DMV3", "0"],
  ["270", "ギタードライブ", "ぎたーどらいぶ", "Handsome JET", "HANDSOMEJET", "GF&DMV3", "0"],
  ["271", "ミラージュ・レジデンス", "みらーじゅれじでんす", "Jimmy Weckl", "JIMMYWECKL", "GF&DMV3", "0"],
  ["272", "七福神", "しちふくじん", "亜熱帯マジ-SKA爆弾", "あねったいまじSKAばくだん", "GF&DMV3", "0"],
  ["273", "全力少年", "ぜんりょくしょうねん", "", "", "GF&DMV3,有名楽曲", "0"],
  ["274", "大和撫子魂", "やまとなでしこだましい", "小坂りゆ", "こさかりゆ", "GF&DMV3,有名楽曲", "0"],
  ["275", "差無来！！", "さむらい", "Des-ROW・組", "DESROWぐみ", "GF&DMV3", "0"],
  ["276", "戻らない恋", "もどらないこい", "ザ・パンサーズ", "ざぱんさーず", "GF&DMV3", "0"],
  ["277", "繚乱ヒットチャート", "りょうらんひっとちゃーと", "ギラギラメガネ団", "ぎらぎらめがねだん", "GF&DMV3", "0"],
  ["278", "虧兎に告ぐ", "きとにつぐ", "あさき", "あさき", "GF&DMV3", "0"],
  ["280", "5-10", "510", "good-cool ft. 近藤葵", "GOODCOOLFTこんどうあおい", "GF&DMV4", "0"],
  ["281", "Charismatic", "CHARISMATIC", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "GF&DMV4", "0"],
  ["282", "DEADMAN'S BED", "DEADMANSBED", "Rotten Blotch", "ROTTENBLOTCH", "GF&DMV4", "0"],
  ["283", "First Date", "FIRSTDATE", "ko-saku", "KOSAKU", "GF&DMV4", "0"],
  ["284", "GORI GORI", "GORIGORI", "ASMAT", "ASMAT", "GF&DMV4", "0"],
  ["285", "How do you feel?", "HOWDOYOUFEEL", "mao", "MAO", "GF&DMV4", "0"],
  ["286", "Immortal Bind", "IMMORTALBIND", "ANTHEM", "ANTHEM", "GF&DMV4,有名楽曲", "0"],
  ["287", "MODEL DD8", "MODELDD8", "Mutsuhiko Izumi feat. Marty Friedman", "MUTSUHIKOIZUMIFEATMARTYFRIEDMAN", "GF&DMV4", "0"],
  ["288", "PRIME LIGHT", "PRIMELIGHT", "TAG", "TAG", "GF&DMV4", "0"],
  ["289", "Raining Sunshine", "RAININGSUNSHINE", "Nina Lee Kaminsky", "NINALEEKAMINSKY", "GF&DMV4", "0"],
  ["290", "REVOLUTION", "RVOLUTIN", "TЁЯRA", "TERRA", "GF&DMV4", "0"],
  ["291", "R#1", "R1", "colors", "COLORS", "GF&DMV4", "0"],
  ["292", "Slang", "SLANG", "Kozo Nakamura", "KOZONAKAMURA", "GF&DMV4", "0"],
  ["293", "Strike Party!!!", "STRIKEPARTY", "BeForU", "BEFORU", "GF&DMV4,有名楽曲", "0"],
  ["294", "Swimming In Love", "SWIMMINGINLOVE", "ナツキ", "なつき", "GF&DMV4", "0"],
  ["295", "TABIDACHI", "TABIDACHI", "古川もとあき", "ふるかわもとあき", "GF&DMV4", "0"],
  ["296", "The Messenger (not decorated)", "THEMESSENGERNOTDECORATED", "orangenoise shortcut", "ORANGENOISESHORTCUT", "GF&DMV4", "0"],
  ["297", "True Love and Valentines", "TRUELOVEANDVALENTINES", "古川もとあき feat. Thomas Howard Lichtenstein", "ふるかわもとあきFEATTHOMASHOWARDLICHTENSTEIN", "GF&DMV4", "0"],
  ["298", "Vertigo", "VERTIGO", "Sis Bond Chit", "SISBONDCHIT", "GF&DMV4", "0"],
  ["299", "Zigzag Life", "ZIGZAGLIFE", "Jimmy Weckl", "JIMMYWECKL", "GF&DMV4", "0"],
  ["300", "murmur twins (guitar pop ver.)", "MURMURTWINSGUITARPOPVER", "yu_tokiwa.djw merge scl.gtr", "YUTOKIWADJWMERGESCLGTR", "GF&DMV4", "0"],
  ["301", "ガラナ", "がらな", "", "", "GF&DMV4,有名楽曲", "0"],
  ["302", "一網打尽", "いちもうだじん", "96", "96", "GF&DMV4", "0"],
  ["303", "太陽〜T・A・I・Y・O〜(ANOTHER SENSE EDITION)", "たいようTAIYOANOTHERSENSEEDITION", "星野奏子", "ほしのかなこ", "GF&DMV4", "0"],
  ["304", "恋は臆病", "こいはおくびょう", "達見 恵", "たつみめぐみ", "GF&DMV4", "0"],
  ["305", "極東史記", "きょくとうしき", "あさき", "あさき", "GF&DMV4", "0"],
  ["307", "A.DOGMA", "ADOGMA", "あさき", "あさき", "GF&DMV5", "0"],
  ["308", "ATOMS", "ATOMS", "Rotten Blotch", "ROTTENBLOTCH", "GF&DMV5", "0"],
  ["309", "Blue Forest", "BLUEFOREST", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV5", "0"],
  ["310", "Dynamis", "DYNAMIS", "千本松 仁", "せんぼんまつじん", "GF&DMV5", "0"],
  ["311", "Electric Lady", "ELECTRICLADY", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV5", "0"],
  ["312", "FOR THE FINAL", "FORTHEFINAL", "あさき", "あさき", "GF&DMV5", "0"],
  ["313", "FORCE Interval Build", "FORCEINTERVALBUILD", "96", "96", "GF&DMV5", "0"],
  ["314", "LAST SCENE", "LASTSCENE", "L.E.D.-G VS. GUHROOVY fw. NO+CHIN", "LEDGVSGUHROOVYFWNOCHIN", "GF&DMV5", "0"],
  ["315", "MU-DAI", "MUDAI", "小野秀幸", "おのひでゆき", "GF&DMV5", "0"],
  ["316", "Mannequin", "MANNEQUIN", "Sis Bond Chit", "SISBONDCHIT", "GF&DMV5", "0"],
  ["317", "Opus Life", "OPUSLIFE", "Taisho", "TAISHO", "GF&DMV5", "0"],
  ["318", "Piece of History", "PIECEOFHISTORY", "TAG", "TAG", "GF&DMV5", "0"],
  ["319", "Power Game", "POWERGAME", "荒牧陽子", "あらまきようこ", "GF&DMV5", "0"],
  ["320", "Rock to Infinity", "ROCKTOINFINITY", "千本松 仁", "せんぼんまつじん", "GF&DMV5", "0"],
  ["321", "TENGU", "TENGU", "Jimmy Weckl", "JIMMYWECKL", "GF&DMV5", "0"],
  ["322", "Terpsichore", "TERPSICHORE", "斉藤由佳", "さいとうゆか", "GF&DMV5", "0"],
  ["323", "VANESSA -転生編-", "VANESSAてんせいへん", "朱雀 VS. TAG", "すざくVSTAG", "GF&DMV5", "0"],
  ["324", "in control", "INCONTROL", "RYDER", "RYDER", "GF&DMV5", "0"],
  ["325", "からふるぱすてる", "からふるぱすてる", "ki☆ki", "KIKI", "GF&DMV5", "0"],
  ["326", "ゴーイング マイ ウェイ！", "ごーいんぐまいうぇい", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GF&DMV5", "0"],
  ["327", "ヒコーキ", "ひこーき", "colors", "COLORS", "GF&DMV5", "0"],
  ["328", "ヒトリアソビ", "ひとりあそび", "iNO", "INO", "GF&DMV5", "0"],
  ["329", "凛として咲く花の如く", "りんとしてさくはなのごとく", "紅色リトマス", "べにいろりとます", "GF&DMV5", "0"],
  ["330", "創聖のアクエリオン", "そうせいのあくえりおん", "", "", "GF&DMV5,有名楽曲", "0"],
  ["331", "流氷の去りて", "りゅうひょうのさりて", "あさき", "あさき", "GF&DMV5", "0"],
  ["332", "田んぼの田", "たんぼのた", "good-cool feat. すわひでお", "GOODCOOLFEATすわひでお", "GF&DMV5", "0"],
  ["333", "真夏の恋は ちゅらちゅらLove☆", "まなつのこいはちゅらちゅらLOVE", "MAKI", "MAKI", "GF&DMV5", "0"],
  ["334", "腐斯偽堕日本", "ふしぎだにっぽん", "Des-ROW・組コアスぺ", "DESROWぐみこあすぺ", "GF&DMV5", "0"],
  ["335", "鏡花水月楼 (GFDM EDITION)", "きょうかすいげつろうGFDMEDITION", "TЁЯRA feat.宇宙戦隊NOIZ", "TERRAFEATうちゅうせんたいNOIZ", "GF&DMV5", "0"],
  ["337", "1/n", "1N", "iri", "IRI", "GF&DMV6", "0"],
  ["338", "Catharsis Garden", "CATHARSISGARDEN", "TЁЯRA", "TERRA", "GF&DMV6", "0"],
  ["339", "Chronos", "CHRONOS", "TAG", "TAG", "GF&DMV6", "0"],
  ["340", "Driven Shooter", "DRIVENSHOOTER", "猫叉Master+", "ねこまたMASTER", "GF&DMV6", "0"],
  ["341", "ENCORE CONQUEST", "ENCORECONQUEST", "Trick Trap +", "TRICKTRAP", "GF&DMV6", "0"],
  ["342", "Highway star", "HIGHWAYSTAR", "小野秀幸 feat. Mercy", "おのひでゆきFEATMERCY", "GF&DMV6", "0"],
  ["343", "I wanna kiss you", "IWANNAKISSYOU", "mao", "MAO", "GF&DMV6", "0"],
  ["344", "Icicles", "ICICLES", "Jimmy Weckl", "JIMMYWECKL", "GF&DMV6", "0"],
  ["345", "Jungle", "JUNGLE", "Mutsuhiko Izumi with Jimmy Weckl", "MUTSUHIKOIZUMIWITHJIMMYWECKL", "GF&DMV6", "0"],
  ["346", "NIL", "NIL", "Nelo", "NELO", "GF&DMV6", "0"],
  ["347", "OVER THE LIMIT！", "OVERTHELIMIT", "伊藤賢治", "いとうけんじ", "GF&DMV6", "0"],
  ["348", "Red", "RED", "Kozo Nakamura", "KOZONAKAMURA", "GF&DMV6", "0"],
  ["349", "Siren", "SIREN", "Sis Bond Chit", "SISBONDCHIT", "GF&DMV6", "0"],
  ["350", "Sky", "SKY", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GF&DMV6", "0"],
  ["351", "four-leaf", "FOURLEAF", "Sis Bond Chit", "SISBONDCHIT", "GF&DMV6", "0"],
  ["352", "humming rabbit", "HUMMINGRABBIT", "mighty puppet", "MIGHTYPUPPET", "GF&DMV6", "0"],
  ["353", "こなもん屋人情歌", "こなもんやにんじょうか", "天下茶屋子", "てんかちゃやこ", "GF&DMV6", "0"],
  ["354", "イジワルなあなた", "いじわるなあなた", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GF&DMV6", "0"],
  ["355", "ガラスの小舟", "がらすのこぶね", "肥塚良彦", "こえづかよしひこ", "GF&DMV6", "0"],
  ["356", "ブルーバード", "ぶるーばーど", "", "", "GF&DMV6,有名楽曲", "0"],
  ["357", "恐怖の右脳改革", "きょうふのうのうかいかく", "96", "96", "GF&DMV6", "0"],
  ["358", "情熱 fun! fun!", "じょうねつFUNFUN", "YAMATO組", "YAMATOぐみ", "GF&DMV6", "0"],
  ["359", "風神雲龍伝", "ふうじんうんりゅうでん", "98", "98", "GF&DMV6", "0"],
  ["361", "Before Daybreak", "BEFOREDAYBREAK", "TAG", "TAG", "XG", "0"],
  ["362", "Believing", "BELIEVING", "阿部靖広", "あべやすひろ", "XG", "0"],
  ["363", "Blue planet", "BLUEPLANET", "Trick Trap", "TRICKTRAP", "XG", "0"],
  ["364", "CALAMITY PHOENIX", "CALAMITYPHOENIX", "96", "96", "XG", "0"],
  ["365", "Confession", "CONFESSION", "Takao Nagatani", "TAKAONAGATANI", "XG", "0"],
  ["366", "Crack", "CRACK", "猫叉Master+", "ねこまたMASTER", "XG", "0"],
  ["367", "Croquette", "CROQUETTE", "Hoshikawa Noboru☆ feat. Clinton Strother and MAT", "HOSHIKAWANOBORUFEATCLINTONSTROTHERANDMAT", "XG", "0"],
  ["368", "Deep Forest", "DEEPFOREST", "Kozo Nakamura", "KOZONAKAMURA", "XG", "0"],
  ["369", "Eau Rouge", "EAUROUGE", "Yosuke Onishi", "YOSUKEONISHI", "XG", "0"],
  ["370", "Egocentricity", "EGOCENTRICITY", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "XG", "0"],
  ["371", "Einherjar", "EINHERJAR", "植松伸夫とわんにゃん☆パニックス", "うえまつのぶおとわんにゃんぱにっくす", "XG", "0"],
  ["372", "Excavation Damage", "EXCAVATIONDAMAGE", "浅田 靖", "あさだやすし", "XG", "0"],
  ["373", "HYPER JET LAND", "HYPERJETLAND", "泉 陸奥彦", "いずみむつひこ", "XG", "0"],
  ["374", "Hunter〜どうしても欲しいもの〜", "HUNTERどうしてもほしいもの", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "XG", "0"],
  ["375", "I Want It All", "IWANTITALL", "Benjamin Franklin", "BENJAMINFRANKLIN", "XG", "0"],
  ["376", "IMI", "IMI", "RYDER", "RYDER", "XG", "0"],
  ["377", "IMITATION TOUCH", "IMITATIONTOUCH", "柴田浩之", "しばたひろゆき", "XG", "0"],
  ["378", "Invincible", "INVINCIBLE", "80Apes", "80APES", "XG", "0"],
  ["379", "KAISER PHOENIX", "KAISERPHOENIX", "96", "96", "XG", "0"],
  ["380", "Keep Ur Dreams", "KEEPURDREAMS", "Mac Nobuka", "MACNOBUKA", "XG", "0"],
  ["381", "Limitless Possibility", "LIMITLESSPOSSIBILITY", "AIKO OI", "AIKOOI", "XG", "0"],
  ["382", "Love☆Carnival", "LOVECARNIVAL", "Atsuki", "ATSUKI", "XG", "0"],
  ["383", "MODEL DD9", "MODELDD9", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG", "0"],
  ["384", "No Way For One Will", "NOWAYFORONEWILL", "TeeJayz,inc.", "TEEJAYZINC", "XG", "0"],
  ["385", "On top of the world", "ONTOPOFTHEWORLD", "LUCA", "LUCA", "XG", "0"],
  ["386", "Piranha", "PIRANHA", "Rotten Blotch", "ROTTENBLOTCH", "XG", "0"],
  ["387", "Shake and Shout！！", "SHAKEANDSHOUT", "伊藤賢治", "いとうけんじ", "XG", "0"],
  ["388", "Sky Runner", "SKYRUNNER", "古川もとあき", "ふるかわもとあき", "XG", "0"],
  ["389", "Stay away", "STAYAWAY", "STIL", "STIL", "XG", "0"],
  ["390", "Trickster", "TRICKSTER", "", "", "XG", "1"],
  ["391", "White wings", "WHITEWINGS", "阿部靖広", "あべやすひろ", "XG", "0"],
  ["392", "X-treme Grade", "XTREMEGRADE", "96", "96", "XG", "0"],
  ["393", "You've Got 2 Get Me", "YOUVEGOT2GETME", "Sota Fujimori feat. RIO", "SOTAFUJIMORIFEATRIO", "XG", "0"],
  ["394", "kiss me", "KISSME", "ピンクターボ", "ぴんくたーぼ", "XG", "0"],
  ["395", "photon", "PHOTON", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "XG", "0"],
  ["396", "さよなら僕自身", "さよならぼくじしん", "PON", "PON", "XG", "0"],
  ["397", "ほしふり", "ほしふり", "Sana", "SANA", "XG", "0"],
  ["398", "クリーンクリーン", "くりーんくりーん", "ブラックカプセル", "ぶらっくかぷせる", "XG", "0"],
  ["399", "ヒカリ", "ひかり", "mao", "MAO", "XG", "0"],
  ["400", "三毛猫JIVE＆ジャイブ", "みけねこJAVEじゃいぶ", "小野秀幸", "おのひでゆき", "XG", "0"],
  ["401", "天庭 おとこのこ編", "てんていおとこのこへん", "あさき", "あさき", "XG", "0"],
  ["402", "太陽の花", "たいようのはな", "DAIHEI", "DAIHEI", "XG", "0"],
  ["403", "幻想花", "げんそうか", "星野奏子", "ほしのかなこ", "XG", "0"],
  ["404", "憧れのボディービル!!", "あこがれのぼでぃーびる", "good-cool ft. すわひでお", "GOODCOOLFTすわひでお", "XG", "0"],
  ["405", "空色デイズ", "そらいろでいず", "中川 翔子", "なかがわしょうこ", "XG,有名楽曲", "0"],
  ["406", "紅蓮の焔", "ぐれんのほのお", "劇団レコードfeat.浅葉リオ", "げきだんれこーどFEATあさばりお", "XG", "0"],
  ["407", "青い鳥", "あおいとり", "Juri", "JURI", "XG", "0"],
  ["409", "AREA 51", "AREA51", "96", "96", "XG2", "0"],
  ["410", "Adrenaline", "ADRENALINE", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "XG2", "0"],
  ["411", "Adverse Criticism", "ADVERSECRITICISM", "浅田 靖", "あさだやすし", "XG2", "0"],
  ["412", "Around 40", "AROUND40", "good-cool ft. すわひでお", "GOODCOOLFTすわひでお", "XG2", "0"],
  ["413", "BEFORE I DECAY", "BEFOREIDECAY", "the GazettE", "THEGAZETTE", "XG2,有名楽曲", "0"],
  ["414", "Bangin' Breaks", "BANGINBREAKS", "Sota Fujimori", "SOTAFUJIMORI", "XG2", "0"],
  ["415", "Big Wave", "BIGWAVE", "Atsuki", "ATSUKI", "XG2", "0"],
  ["416", "Brown blizzard", "BROWNBLIZZARD", "Trick Trap", "TRICKTRAP", "XG2", "0"],
  ["417", "Chance", "CHANCE", "Aimee Blackschleger", "AIMEEBLACKSCHLEGER", "XG2", "0"],
  ["418", "Chinese Snowy Dance", "CHINESESNOWYDANCE", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG2", "0"],
  ["419", "Come Back Alive", "COMEBACKALIVE", "AIKO OI", "AIKOOI", "XG2", "0"],
  ["420", "DAWN", "DAWN", "Melodyout", "MELODYOUT", "XG2", "0"],
  ["421", "DESTINY", "DESTINY", "GALNERYUS", "GALNERYUS", "XG2,有名楽曲", "0"],
  ["422", "EXCELSIOR DIVE", "EXCELSIORDIVE", "TAG", "TAG", "XG2", "0"],
  ["423", "HIT IN THE USA", "HITINTHEUSA", "", "", "XG2,有名楽曲", "0"],
  ["424", "I can be!!", "ICANBE", "Hiromixxx", "HIROMIXXX", "XG2", "0"],
  ["425", "Illuminati 〜光を求める者たち〜", "ILLUMINATIひかりをもとめるものたち", "Dear Breeze Studio", "DEARBREEZESTUDIO", "XG2", "0"],
  ["426", "Jailbreak", "JAILBREAK", "Kozo Nakamura", "KOZONAKAMURA", "XG2", "0"],
  ["427", "Lepton", "LEPTON", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "XG2", "0"],
  ["428", "Love Rox!", "LOVEROX", "Takao Nagatani", "TAKAONAGATANI", "XG2", "0"],
  ["429", "Pink Bird", "PINKBIRD", "肥塚良彦", "こえづかよしひこ", "XG2", "0"],
  ["430", "REALIZE", "REALIZE", "Qrispy Joyeuse feat.YOKO ARAMAKI", "QRISPYJOYEUSEFEATYOKOARAMAKI", "XG2", "0"],
  ["431", "Right on time (Ryu☆Remix)", "RIGHTONTIMERYUREMIX", "Ryu☆", "RYU", "XG2", "0"],
  ["432", "SIX DIMENSION", "SIXDIMENSION", "96", "96", "XG2", "0"],
  ["433", "Sacred Oath (GFDM EDITION)", "SACREDOATHGFDMEDITION", "TЁЯRA", "TERRA", "XG2", "0"],
  ["434", "Spiral Wind", "SPIRALWIND", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG2", "0"],
  ["435", "Spring Pain", "SPRINGPAIN", "seiya-murai feat. ALT", "SEIYAMURAIFEATALT", "XG2", "0"],
  ["436", "The 勇気", "THEゆうき", "ピンクターボ", "ぴんくたーぼ", "XG2", "0"],
  ["437", "Victory!", "VICTORY", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "XG2", "0"],
  ["438", "X-Plan", "XPLAN", "Tom-H@ck feat.Nadia", "TOMHCKFEATNADIA", "XG2", "0"],
  ["439", "blue moon", "BLUEMOON", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG2", "0"],
  ["440", "chAngE", "CHANGE", "", "", "XG2,有名楽曲", "0"],
  ["441", "cosmic agenda", "COSMICAGENDA", "TOMOSUKE feat. Jazzin'park & frances maya", "TOMOSUKEFEATJAZZINPARKFRANCESMAYA", "XG2", "0"],
  ["442", "drop", "DROP", "RYDER", "RYDER", "XG2", "0"],
  ["443", "gloom", "GLOOM", "w/Akino", "WAKINO", "XG2", "0"],
  ["444", "no way ...", "NOWAY", "colors", "COLORS", "XG2", "0"],
  ["445", "じょいふる", "じょいふる", "", "", "XG2,有名楽曲", "0"],
  ["446", "たからもの", "たからもの", "セリカ＆エリカ", "せりかえりか", "XG2", "0"],
  ["447", "アンマー", "あんまー", "かりゆし58", "かりゆし58", "XG2,有名楽曲", "0"],
  ["448", "イバラノミチ", "いばらのみち", "DAIHEI", "DAIHEI", "XG2", "0"],
  ["449", "ゲームより愛を込めて", "げーむよりあいをこめて", "小林信一", "こばやししんいち", "XG2", "0"],
  ["450", "サヨナラナミダ", "さよならなみだ", "Qrispy Joybox feat.mao", "QRISPYJOYBOXFEATMAO", "XG2", "0"],
  ["451", "ダイヤモンドロマンス", "だいやもんどろまんす", "Twinkle☆berry", "TWINKLEBERRY", "XG2", "0"],
  ["452", "ナキムシの凱旋", "なきむしのがいせん", "PON", "PON", "XG2", "0"],
  ["453", "バタフライ狂想曲", "ばたふらいきょうそうきょく", "THE UNIQUE STAR", "THEUNIQUESTAR", "XG2,有名楽曲", "0"],
  ["454", "ヴィーナスとジーザス", "ゔぃーなすとじーざす", "", "", "XG2,有名楽曲", "0"],
  ["455", "優勢オーバードーズ", "ゆうせいおーばーどーず", "PON", "PON", "XG2", "0"],
  ["456", "前髪", "まえがみ", "さかもとえいぞう&劇団レコード", "さかもとえいぞうげきだんれこーど", "XG2", "0"],
  ["457", "卒業", "そつぎょう", "ガガガSP", "がががSP", "XG2,有名楽曲", "0"],
  ["458", "夢について TYPE B", "ゆめについてTYPEB", "小野秀幸 feat. 96", "おのひでゆきFEAT96", "XG2", "0"],
  ["459", "夢について TYPE C", "ゆめについてTYPEC", "小野秀幸 feat. 岡本裕美", "おのひでゆきFEATおかもとひろみ", "XG2", "0"],
  ["460", "幻想雷神記", "げんそうらいじんき", "98", "98", "XG2", "0"],
  ["461", "明鏡止水 - Stop The Fire Mix", "めいきょうしすいSTOPTHEFIREMIX", "Sota Fujimori feat. Mutsuhiko Izumi", "SOTAFUJIMORIFEATMUTSUHIKOIZUMI", "XG2", "0"],
  ["462", "牛乳特急便 -まとめきれない Romantic style-", "ぎゅうにゅうとっきゅうびんまとめきれないROMANTICSTYLE", "キャプテンメタル", "きゃぷてんめたる", "XG2", "0"],
  ["463", "百鬼夜行", "ひゃっきやこう", "96", "96", "XG2", "0"],
  ["464", "紫の月", "むらさきのつき", "阿部靖広", "あべやすひろ", "XG2", "0"],
  ["465", "行き過ぎて後に", "いきすぎてあとに", "あさき", "あさき", "XG2", "0"],
  ["466", "衝動がえがいた どうしようもないストーリー", "しょうどうがえがいたどうしようもないすとーりー", "2B-Waves", "2BWAVES", "XG2", "0"],
  ["467", "風／雷", "ふうらい", "world sequence", "WORLDSEQUENCE", "XG2", "0"],
  ["468", "黒髪乱れし修羅となりて", "くろかみみだれししゅらとなりて", "村正クオリア", "むらまさくおりあ", "XG2", "0"],
  ["470", "800nm", "800NM", "Another Infinity(Ryu☆×Starving Trancer)", "ANOTHERINFINITYRYUSTARVINGTRANCER", "XG3", "0"],
  ["471", "CHAIN REACTION feat.NO+CHIN", "CHAINREACTIONFEATNOCHIN", "Katana Sounds Vs. L.E.D.-G", "KATANASOUNDSVSLEDG", "XG3", "0"],
  ["472", "Cosmic Hurricane (GFDM ver.)", "COSMICHURRICANEGFDMVER", "TAG feat. Mutsuhiko Izumi", "TAGFEATMUTSUHIKOIZUMI", "XG3", "0"],
  ["473", "DOUBLE IMPACT", "DOUBLEIMPACT", "DOUBLE IMPACT", "DOUBLEIMPACT", "XG3", "0"],
  ["474", "Devil Fish Dumpling", "DEVILFISHDUMPLING", "96", "96", "XG3", "0"],
  ["475", "Dragontail Butterfly", "DRAGONTAILBUTTERFLY", "Tom-H@ck feat.Nadia", "TOMHCKFEATNADIA", "XG3", "0"],
  ["476", "ETERNAL BLAZE", "ETERNALBLAZE", "", "", "XG3,有名楽曲", "0"],
  ["477", "Eastern Lariat", "EASTERNLARIAT", "good-cool", "GOODCOOL", "XG3", "0"],
  ["478", "FLOWER -TLION69 Remix-", "FLOWERTLION69REMIX", "DJ YOSHITAKA feat. TLION69", "DJYOSHITAKAFEATTLION69", "XG3", "0"],
  ["479", "FRIENDSHIP", "FRIENDSHIP", "PON", "PON", "XG3", "0"],
  ["480", "Freeky Technique", "FREEKYTECHNIQUE", "ALLY & DIAZ Feat. KOJIMA & SATOSHI (山嵐)", "ALLYDIAZFEATKOJIMASATOSHIやまあらし", "XG3", "0"],
  ["481", "Genesis Creation Narrative", "GENESISCREATIONNARRATIVE", "AIKO OI", "AIKOOI", "XG3", "0"],
  ["482", "Give Me MORE!!", "GIVEMEMORE", "Sota Fujimori", "SOTAFUJIMORI", "XG3", "0"],
  ["483", "Gong！", "GONG", "Dear Breeze Studio", "DEARBREEZESTUDIO", "XG3", "0"],
  ["484", "Graviton", "GRAVITON", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "XG3", "0"],
  ["485", "Hard distance", "HARDDISTANCE", "桜庭 統", "さくらばす", "XG3", "0"],
  ["486", "I'm so Happy (Rockin' ver.)", "IMSOHAPPYROCKINVER", "Ryu☆", "RYU", "XG3", "0"],
  ["487", "LISTEN TO THE STEREO!!", "LISTENTOTHESTEREO", "", "", "XG3,有名楽曲", "0"],
  ["488", "LOVE WAR!!", "LOVEWAR", "Takao Nagatani", "TAKAONAGATANI", "XG3", "0"],
  ["489", "MODEL DD10", "MODELDD10", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG3", "0"],
  ["490", "Moon of Muse", "MOONOFMUSE", "鈴木健治", "すずきけんじ", "XG3", "0"],
  ["491", "NEW LEGEND", "NEWLEGEND", "GALNERYUS", "GALNERYUS", "XG3,有名楽曲", "0"],
  ["492", "ONLY ONE", "ONLYONE", "TLION69", "TLION69", "XG3", "0"],
  ["493", "Orange Flower Garden", "ORANGEFLOWERGARDEN", "肥塚良彦", "こえづかよしひこ", "XG3", "0"],
  ["494", "POWER", "POWER", "Thomas Howard Lichtenstein", "THOMASHOWARDLICHTENSTEIN", "XG3", "0"],
  ["495", "Plum", "PLUM", "肥塚良彦", "こえづかよしひこ", "XG3", "0"],
  ["496", "Predator's Crypto Pt.1", "PREDATORSCRYPTOPT1", "96", "96", "XG3", "0"],
  ["497", "Predator's Crypto Pt.2", "PREDATORSCRYPTOPT2", "96", "96", "XG3", "0"],
  ["498", "Raidillon", "RAIDILLON", "Yosuke Onishi", "YOSUKEONISHI", "XG3", "0"],
  ["499", "RePrise", "REPRISE", "SHOGO", "SHOGO", "XG3", "0"],
  ["500", "Restart", "RESTART", "SHOGO", "SHOGO", "XG3", "0"],
  ["501", "Riot of Color", "RIOTOFCOLOR", "TAG", "TAG", "XG3", "0"],
  ["502", "Rush!!", "RUSH", "kors k feat.吉河順央", "KORSKFEATよしかわすなお", "XG3", "0"],
  ["503", "SCREW DRIVER", "SCREWDRIVER", "96", "96", "XG3", "0"],
  ["504", "Shout!!", "SHOUT", "Qrispy Joybox feat.mao", "QRISPYJOYBOXFEATMAO", "XG3", "0"],
  ["505", "Snow Goose GFDM ver.", "SNOWGOOSEGFDMVER", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG3", "0"],
  ["506", "Snowy India", "SNOWYINDIA", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "XG3", "0"],
  ["507", "Starlight Parade", "STARLIGHTPARADE", "肥塚良彦", "こえづかよしひこ", "XG3", "0"],
  ["508", "Summer Holiday", "SUMMERHOLIDAY", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "XG3", "0"],
  ["509", "Xenon", "XENON", "千本松 仁", "せんぼんまつじん", "XG3", "0"],
  ["510", "concon〜INAReMIX〜", "CONCONINAREMIX", "S-C-U with OJ", "SCUWITHOJ", "XG3", "0"],
  ["511", "overviews", "OVERVIEWS", "vox", "VOX", "XG3", "0"],
  ["512", "serial number", "SERIALNUMBER", "ピンクターボ", "ぴんくたーぼ", "XG3", "0"],
  ["513", "snow prism (GFDM ver.)", "SNOWPRISMGFDMVER", "Qrispy Joybox", "QRISPYJOYBOX", "XG3", "0"],
  ["514", "spectrum", "SPECTRUM", "Takao Nagatani", "TAKAONAGATANI", "XG3", "0"],
  ["515", "つぼみ", "つぼみ", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "XG3", "0"],
  ["516", "アーリマン", "あーりまん", "millll", "MILLLL", "XG3", "0"],
  ["517", "ギタ・ドラ・jubeat大夏祭りのテーマ", "ぎたどらJUBEATだいなつまつりのてーま", "DNM盛り上げ隊", "DNMもりあげたい", "XG3", "0"],
  ["518", "サムライハート （Some Like It Hot!!）", "さむらいはーとSOMELIKEITHOT", "", "", "XG3,有名楽曲", "0"],
  ["519", "タイムカプセル", "たいむかぷせる", "肥塚良彦", "こえづかよしひこ", "XG3", "0"],
  ["520", "ハートジャック", "はーとじゃっく", "NANA", "NANA", "XG3", "0"],
  ["521", "ヤミクラ", "やみくら", "PON", "PON", "XG3", "0"],
  ["522", "侯爵夫人の陰謀", "こうしゃくふじんのいんぼう", "劇団レコード feat.浅葉リオ", "げきだんれこーどFEATあさばりお", "XG3", "0"],
  ["523", "双つ雲と暁の奏", "ふたつくもとあかつきのかなで", "world sequence", "WORLDSEQUENCE", "XG3", "0"],
  ["524", "夏・KOI・ムッシュ!!", "なつこいむっしゅ", "ビーチサンダルズ", "びーちさんだるず", "XG3", "0"],
  ["525", "夏祭り", "なつまつり", "", "", "XG3", "1"],
  ["526", "幸せのかたち", "しあわせのかたち", "あさき", "あさき", "XG3", "0"],
  ["527", "恋閃繚乱", "れんせんりょうらん", "2B-Waves", "2BWAVES", "XG3", "0"],
  ["528", "星夢", "ほしゆめ", "Dormir", "DORMIR", "XG3", "0"],
  ["529", "暗黒舞踏会", "あんこくぶとうかい", "Dragon Guardian", "DRAGONGUARDIAN", "XG3,有名楽曲", "0"],
  ["530", "歌の翼", "うたのつばさ", "あーたん", "あーたん", "XG3", "0"],
  ["531", "流星☆JUMP！", "りゅうせいJUMP", "Tatsh feat.REN", "TATSHFEATREN", "XG3", "0"],
  ["532", "笑ってたいんだ", "わらってたいんだ", "", "", "XG3,有名楽曲", "0"],
  ["533", "紅焔", "こうれん", "PON", "PON", "XG3", "0"],
  ["534", "群青と流星", "ぐんじょうとりゅうせい", "2B-Waves", "2BWAVES", "XG3", "0"],
  ["535", "耳たぶ2号", "みみたぶ2ごう", "", "", "XG3,有名楽曲", "0"],
  ["536", "逆ナンされたのにドタキャン!!", "ぎゃくなんされたのにどたきゃん", "good-cool ft. すわひでお", "GOODCOOLFTすわひでお", "XG3", "0"],
  ["537", "隅田川夏恋歌〜納涼mix", "すみだがわかれんかのうりょうMIX", "seiya-murai feat.ALT", "SEIYAMURAIFEATALT", "XG3", "0"],
  ["539", "0時20分のRoulette", "0じ20ふんのROULETTE", "ApachE with T_da", "APACHEWITHTDA", "GITADORA", "0"],
  ["540", "Arena Sexarboris", "ARENASEXARBORIS", "Akhuta", "AKHUTA", "GITADORA", "0"],
  ["541", "Awaken Ver.G", "AWAKENVERG", "KOHTA", "KOHTA", "GITADORA", "0"],
  ["542", "BLUE BOOTS", "BLUEBOOTS", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["543", "Beautiful Dream", "BEAUTIFULDREAM", "REDALiCE feat. anporin", "REDALICEFEATANPORIN", "GITADORA", "0"],
  ["544", "Cassis", "CASSIS", "肥塚良彦", "こえづかよしひこ", "GITADORA", "0"],
  ["545", "Crazy blooms", "CRAZYBLOOMS", "桜庭　統", "さくらばす", "GITADORA", "0"],
  ["546", "DIGITAL GIRL", "DIGITALGIRL", "石阪久美子", "いしさかくみこ", "GITADORA", "0"],
  ["547", "DRAGON KILLER", "DRAGONKILLER", "96 vs. Mutsuhiko Izumi", "96VSMUTSUHIKOIZUMI", "GITADORA", "0"],
  ["548", "Don't Break Up", "DONTBREAKUP", "Sota Fujimori", "SOTAFUJIMORI", "GITADORA", "0"],
  ["549", "Elemental Creation -GITADO ROCK ver.-", "ELEMENTALCREATIONGITADOROCKVER", "dj TAKA meets DJ YOSHITAKA ft.guit.good-cool", "DJTAKAMEETSDJYOSHITAKAFTGUITGOODCOOL", "GITADORA", "0"],
  ["550", "Empathetic", "EMPATHETIC", "Sota÷Des", "SOTADES", "GITADORA", "0"],
  ["551", "Endless Chain ～2人でトリガーをひこう～", "ENDLESSCHAINふたりでとりがーをひこう", "私立BEMANI学園軽音部", "しりつBEMANIがくえんけいおんぶ", "GITADORA", "0"],
  ["552", "Engraved Mark", "ENGRAVEDMARK", "Ryu☆ ∞ Des-ROW", "RYUDESROW", "GITADORA", "0"],
  ["553", "Evans -TLION69 Remix-", "EVANSTLION69REMIX", "DJ YOSHITAKA feat. TLION69", "DJYOSHITAKAFEATTLION69", "GITADORA", "0"],
  ["554", "Factor of adhesion", "FACTOROFADHESION", "浅田 靖 (ノイジークローク)", "あさだやすしのいじーくろーく", "GITADORA", "0"],
  ["555", "Fat snail", "FATSNAIL", "NECOMATA MODIFY SALVATION feat.シシドヒナタ", "NECOMATAMODIFYSALVATIONFEATししどひなた", "GITADORA", "0"],
  ["556", "Fly with me", "FLYWITHME", "TAG", "TAG", "GITADORA", "0"],
  ["557", "GAIA -GITADORA EDITION-", "GAIAGITADORAEDITION", "猫叉L.E.D.Master+", "ねこまたLEDMASTER", "GITADORA", "0"],
  ["558", "GIGA BREAK", "GIGABREAK", "96", "96", "GITADORA", "0"],
  ["559", "Give Us Kiss!", "GIVEUSKISS", "sugerless suger", "SUGERLESSSUGER", "GITADORA", "0"],
  ["560", "Grapes", "GRAPES", "肥塚良彦", "こえづかよしひこ", "GITADORA", "0"],
  ["561", "HEART BEAT FORMULA (GITADORA Ver.)", "HEARTBEATFORMULAGITADORAVER", "TAG feat. 96", "TAGFEAT96", "GITADORA", "0"],
  ["562", "HYENA (Live Edit feat. 96)", "HYENALIVEEDITFEAT96", "Hommarju", "HOMMARJU", "GITADORA", "0"],
  ["563", "Hyperseven type K", "HYPERSEVENTYPEK", "小林信一", "こばやししんいち", "GITADORA", "0"],
  ["564", "IX -GITADOROCK ver.-", "9GITADOROCKVER", "dj TAKA VS DJ TOTTO feat.藍 & good-cool", "DJTAKAVSDJTOTTOFEATあいGOODCOOL", "GITADORA", "0"],
  ["565", "Jasper", "JASPER", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "GITADORA", "0"],
  ["566", "Joyeuse", "JOYEUSE", "ke-ji", "KEJI", "GITADORA", "0"],
  ["567", "Last Song", "LASTSONG", "AIKO OI", "AIKOOI", "GITADORA", "0"],
  ["568", "Like&Love", "LIKELOVE", "Tatsh feat. REN", "TATSHFEATREN", "GITADORA", "0"],
  ["569", "Link up", "LINKUP", "chocochips", "CHOCOCHIPS", "GITADORA", "0"],
  ["570", "MANDARA", "MANDARA", "さたな", "さたな", "GITADORA", "0"],
  ["571", "MODEL FT3", "MODELFT3", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["572", "Metallic", "METALLIC", "Sota Fujimori", "SOTAFUJIMORI", "GITADORA", "0"],
  ["573", "Mighty Wind", "MIGHTYWIND", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["574", "Mother Tree", "MOTHERTREE", "AIKO OI", "AIKOOI", "GITADORA", "0"],
  ["575", "Never Look Back in Sorrow", "NEVERLOOKBACKINSORROW", "AIKO OI", "AIKOOI", "GITADORA", "0"],
  ["576", "Obsidian", "OBSIDIAN", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "GITADORA", "0"],
  ["577", "PATRIOT'S DREAM(美しく花と散れ)", "PATRIOTSDREAMうつくしくはなとちれ", "X.Y.Z.→A", "XYZA", "GITADORA,有名楽曲", "0"],
  ["578", "PUNISHER", "PUNISHER", "TAG×PON", "TAGPON", "GITADORA", "0"],
  ["579", "Polaris", "POLARIS", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["580", "RAGNAROK", "RAGNAROK", "96", "96", "GITADORA", "0"],
  ["581", "ROCKET MAN", "ROCKETMAN", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["582", "Red haze", "REDHAZE", "Trick Trap", "TRICKTRAP", "GITADORA", "0"],
  ["583", "Return of the throne", "RETURNOFTHETHRONE", "ニケ featuring neko", "にけFEATURINGNEKO", "GITADORA", "0"],
  ["584", "Rosetta Stone", "ROSETTASTONE", "TAG", "TAG", "GITADORA", "0"],
  ["585", "S. LAUNCHER", "SLAUNCHER", "STRAND", "STRAND", "GITADORA", "0"],
  ["586", "SPACE DRIVER", "SPACEDRIVER", "みーちゃん", "みーちゃん", "GITADORA", "0"],
  ["587", "STULTI", "STULTI", "MAX MAXIMIZER VS DJ TOTTO", "MAXMAXIMIZERVSDJTOTTO", "GITADORA", "0"],
  ["588", "Screaming Your Faith!!!", "SCREAMINGYOURFAITH", "itoken vs. 96", "ITOKENVS96", "GITADORA", "0"],
  ["589", "Second Limit", "SECONDLIMIT", "MY FIRST STORY", "MYFIRSTSTORY", "GITADORA,有名楽曲", "0"],
  ["590", "Shining Wings", "SHININGWINGS", "柳本愛加", "やなもとあいか", "GITADORA", "0"],
  ["591", "Shining Wizard", "SHININGWIZARD", "96", "96", "GITADORA", "0"],
  ["592", "Spanish Snowy Dance (daybreak ver.)", "SPANISHSNOWYDANCEDAYBREAKVER", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA", "0"],
  ["593", "Speeders", "SPEEDERS", "kors k feat.吉河順央", "KORSKFEATよしかわすなお", "GITADORA", "0"],
  ["594", "Squeeze -GITADORA Mix-", "SQUEEZEGITADORAMIX", "VENUS feat. Mutsuhiko Izumi", "VENUSFEATMUTSUHIKOIZUMI", "GITADORA", "0"],
  ["595", "Stella Sinistra", "STELLASINISTRA", "Akhuta Philharmonic Orchestra", "AKHUTAPHILHARMONICORCHESTRA", "GITADORA", "0"],
  ["596", "Summer Lady", "SUMMERLADY", "Atsuki", "ATSUKI", "GITADORA", "0"],
  ["597", "Synergy For Angels (GITADORA Ver.)", "SYNERGYFORANGELSGITADORAVER", "TAG×U1-ASAMi", "TAGU1ASAMI", "GITADORA", "0"],
  ["598", "TRICK", "TRICK", "永谷 喬夫", "ながたにたかお", "GITADORA", "0"],
  ["599", "Triple Journey -OJ EDITION-", "TRIPLEJOURNEYOJEDITION", "Triumvirate", "TRIUMVIRATE", "GITADORA", "0"],
  ["600", "VOICE", "VOICE", "久保田 祥平", "くぼたしょうへい", "GITADORA", "0"],
  ["601", "Veneficus Verticis", "VENEFICUSVERTICIS", "Akhuta", "AKHUTA", "GITADORA", "0"],
  ["602", "Virga Gigantum", "VIRGAGIGANTUM", "Akhuta", "AKHUTA", "GITADORA", "0"],
  ["603", "heron -GITADOROCK ver.-", "HERONGITADOROCKVER", "S-C-U with OJ", "SCUWITHOJ", "GITADORA", "0"],
  ["604", "memento mori -intro-", "MEMENTOMORIINTRO", "あさき", "あさき", "GITADORA", "0"],
  ["605", "nightbird lost wing (GITADORA ver.)", "NIGHTBIRDLOSTWINGGITADORAVER", "猫叉Master+", "ねこまたMASTER", "GITADORA", "0"],
  ["606", "no where now here", "NOWHERENOWHERE", "TLION69", "TLION69", "GITADORA", "0"],
  ["607", "quaver♪ ギタドラ ver.", "QUAVERぎたどらVER", "Risk Junk Φ", "RISKJUNKΦ", "GITADORA", "0"],
  ["608", "solitude", "SOLITUDE", "TAG", "TAG", "GITADORA", "0"],
  ["609", "†渚の小悪魔ラヴリィ～レイディオ† (GITADORA ver.)", "なぎさのこあくまらぶりーれいでぃおGITADORAVER", "夏色ビキニのPrim", "なついろびきにのPRIM", "GITADORA", "0"],
  ["610", "いきもの失格", "いきものしっかく", "あさきのくりむ童話", "あさきのくりむどうわ", "GITADORA", "0"],
  ["611", "お米の美味しい炊き方、そしてお米を食べることによるその効果。", "おこめのおいしいたきかたそしておこめをたべることによるそのこうか", "大日本鉄倶楽部【あさき&96】", "だいにほんてつくらぶあさき96", "GITADORA", "0"],
  ["612", "ぐっばい my crybaby", "ぐっばいMYCRYBABY", "鈴木 友里絵", "すずきゆりえ", "GITADORA", "0"],
  ["613", "こわれそうなもの", "こわれそうなもの", "永谷 喬夫", "ながたにたかお", "GITADORA", "0"],
  ["614", "ちくわパフェだよ☆ＣＫＰ", "ちくわぱふぇだよCKP", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA", "0"],
  ["615", "めうめうぺったんたん！！", "めうめうぺったんたん", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA", "0"],
  ["616", "もぎたてANGEL", "もぎたてANGEL", "YAMATO組－", "YAMATOぐみ", "GITADORA", "0"],
  ["617", "アルストロメリア (GITADORA Ver.)", "あるすとろめりあGITADORAVER", "TAG", "TAG", "GITADORA", "0"],
  ["618", "ガラス越し→バイなう", "がらすごしばいなう", "seiya-murai feat.ALT", "SEIYAMURAIFEATALT", "GITADORA", "0"],
  ["619", "キケンな果実", "きけんなかじつ", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GITADORA", "0"],
  ["620", "キルト", "きると", "Des-Sana+wpt9", "DESSANAWPT9", "GITADORA", "0"],
  ["621", "デストロイマーチ", "ですとろいまーち", "桜華", "おうか", "GITADORA", "0"],
  ["622", "デッドボヲルdeホームラン", "でっどぼをるDEほーむらん", "猫叉Masterβ2", "ねこまたMASTERΒ2", "GITADORA", "0"],
  ["623", "ドリーム・キッス", "どりーむきっす", "阿部靖広 feat. Strawberry Wink", "あべやすひろFEATSTRAWBERRYWINK", "GITADORA", "0"],
  ["624", "ノンフィクションワールド", "のんふぃくしょんわーるど", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GITADORA", "0"],
  ["625", "フレッフレー♪熱血チアガール", "ふれっふれーねっけつちあがーる", "裏マドンナだ！Primちゃん", "うらまどんなだPRIMちゃん", "GITADORA", "0"],
  ["626", "ホーンテッド★メイドランチ", "ほーんてっどめいどらんち", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA", "0"],
  ["627", "ボクらのトリップデイズ", "ぼくらのとりっぷでいず", "2B-Waves", "2BWAVES", "GITADORA", "0"],
  ["628", "ボンビースキップ!!", "ぼんびーすきっぷ", "good-cool ft. すわひでお", "GOODCOOLFTすわひでお", "GITADORA", "0"],
  ["629", "ポップミュージック続論", "ぽっぷんみゅーじっくぞくろん", "ギラギラメガネ楽団 feat.MAKI", "ぎらぎらめがねがくだんFEATMAKI", "GITADORA", "0"],
  ["630", "マインド・ゲーム", "まいんどげーむ", "96 with メカショッチョー", "96WITHめかしょっちょー", "GITADORA", "0"],
  ["631", "マネマネサイコトロピック", "まねまねさいことろぴっく", "かいりきベア", "かいりきべあ", "GITADORA,有名楽曲", "0"],
  ["632", "ラキラキ (GITADORA Ver.)", "らきらきGITADORAVER", "Mutsuhiko Izumi & S-C-U", "MUTSUHIKOIZUMISCU", "GITADORA", "0"],
  ["633", "ロックスターと魔法のランプ", "ろっくすたーとまほうのらんぷ", "ピロカルピン", "ぴろかるぴん", "GITADORA,有名楽曲", "0"],
  ["634", "三毛猫ロックンロール", "みけねころっくんろーる", "マジSKA", "まじSKA", "GITADORA", "0"],
  ["635", "俺と愛とロック", "おれとあいとろっく", "millll", "MILLLL", "GITADORA", "0"],
  ["636", "僕とサヨナラの合図", "ぼくとさよならのあいず", "久保田 祥平", "くぼたしょうへい", "GITADORA", "0"],
  ["637", "元禄花吹雪", "げんろくはなふぶき", "泉 陸奥彦", "いずみむつひこ", "GITADORA", "0"],
  ["638", "冬色", "ふゆいろ", "岡田知亜美", "おかだちあみ", "GITADORA", "0"],
  ["639", "創世ノート", "そうせいのーと", "PON+wac", "PONWAC", "GITADORA", "0"],
  ["640", "去る金合戦", "さるかねがっせん", "あさきのくりむ童話", "あさきのくりむどうわ", "GITADORA", "0"],
  ["641", "叫声", "きょうせい", "己龍", "きりゅう", "GITADORA,有名楽曲", "0"],
  ["642", "君と同じ季節の下", "きみとおなじきせつのした", "鈴木 友里絵", "すずきゆりえ", "GITADORA", "0"],
  ["643", "夜咄ディセイブ", "よばなしでぃせいぶ", "じん", "じん", "GITADORA,有名楽曲", "0"],
  ["644", "天ノ弱", "あまのじゃく", "164", "164", "GITADORA,有名楽曲", "0"],
  ["645", "少年リップルズ", "しょうねんりっぷるず", "常盤ゆう", "ときわゆう", "GITADORA", "0"],
  ["646", "情操ディストピア", "じょうそうでぃすとぴあ", "mami", "MAMI", "GITADORA", "0"],
  ["647", "愛と勇気の三度笠ポン太", "あいとゆうきのさんどがさぽんた", "荒牧陽子", "あらまきようこ", "GITADORA", "0"],
  ["648", "愛は不死鳥の様に", "あいはふちちょうのように", "真紅の薔薇の騎士Prim", "しんくのばらのきしPRIM", "GITADORA", "0"],
  ["649", "戦場のタクトシュトック", "せんじょうのたくとしゅとっく", "工藤吉三(ベイシスケイプ)", "くどうきちぞうべいしすけいぷ", "GITADORA", "0"],
  ["650", "振動デザイア", "しょうどうでざいあ", "めろでぃーリアン", "めろでぃーりあん", "GITADORA", "0"],
  ["651", "放課後ストライド", "ほうかごすとらいど", "Last Note.", "LASTNOTE", "GITADORA,有名楽曲", "0"],
  ["652", "晴天Bon Voyage", "せいてんBONVOYAGE", "TOMOSUKE × seiya-murai feat. ALT", "TOMOSUKESEIYAMURAIFEATALT", "GITADORA", "0"],
  ["653", "最終回STORY", "さいしゅうかいSTORY", "MY FIRST STORY", "MYFIRSTSTORY", "GITADORA,有名楽曲", "0"],
  ["654", "此岸の戯事", "しがんのざれごと", "Akhuta", "AKHUTA", "GITADORA", "0"],
  ["655", "狂喜宴舞", "きょうきえんぶ", "栗須承之介", "くりすしょうのすけ", "GITADORA", "0"],
  ["656", "猫侍の逆襲", "ねこざむらいのぎゃくしゅう", "猫叉Master", "ねこまたMASTER", "GITADORA", "0"],
  ["657", "白虎転生録", "びゃっこてんせいろく", "98", "98", "GITADORA", "0"],
  ["658", "空蒼ランデヴー", "くうそうらんでぶー", "SIN(ex.Kagrra", "SINEXKAGRRA", "GITADORA", "0"],
  ["659", "羽根亡キ少女唄", "はねなきしょうじょうた", "純情ディスコード", "じゅんじょうでぃすこーど", "GITADORA", "0"],
  ["660", "虹色の花", "にじいろのはな", "Akhuta y OJ", "AKHUTAYOJ", "GITADORA", "0"],
  ["661", "見習い天使と星降りの丘", "みならいてんしとほしふりのおか", "DJ TOTTO", "DJTOTTO", "GITADORA", "0"],
  ["662", "轟け!恋のビーンボール!!～96バット砲炸裂!GITADORAシリーズMVP弾!～", "とどろけこいのぴんぼーる96ばっとほうさくれつGITADORAしりーずMVPだん", "ダイナミック野球兄弟 v.s. クロスファイヤーPrim", "だいなみっくやきゅうきょうだいVSくろすふぁいやーPRIM", "GITADORA", "0"],
  ["663", "辞世テンプレート", "じせいてんぷれーと", "ギラギラ眼帯団", "ぎらぎらがんたいだん", "GITADORA", "0"],
  ["664", "迎撃のフォルテ", "げいげきのふぉるて", "めろでぃーリアン", "めろでぃーりあん", "GITADORA", "0"],
  ["665", "野球の遊び方 そしてその歴史 ～決定版～", "やきゅうのあそびかたそしてそのれきしけっていばん", "あさき大監督", "あさきだいかんとく", "GITADORA", "0"],
  ["666", "金輪際のエレジー", "こんりんざいのえれじー", "劇団レコードfeat.浅葉リオ", "げきだんれこーどFEATあさばりお", "GITADORA", "0"],
  ["667", "雨ノチHello", "あめのちHELLO", "TLION69", "TLION69", "GITADORA", "0"],
  ["668", "雷君", "らいくん", "PON", "PON", "GITADORA", "0"],
  ["670", "Cherry", "CHERRY", "肥塚良彦", "こえづかよしひこ", "GITADORA OverDrive", "0"],
  ["671", "Cleopatrysm", "CLEOPATRYSM", "ピラミッ℃", "ぴらみっ", "GITADORA OverDrive", "0"],
  ["672", "Colors", "COLORS", "鈴木 友里絵", "すずきゆりえ", "GITADORA OverDrive", "0"],
  ["673", "Crystal Toybox", "CRYSTALTOYBOX", "OJ ENSEMBLE", "OJENSEMBLE", "GITADORA OverDrive", "0"],
  ["674", "DEATH BRINGER", "DEATHBRINGER", "96", "96", "GITADORA OverDrive", "0"],
  ["675", "HYDRA", "HYDRA", "96", "96", "GITADORA OverDrive", "0"],
  ["676", "Idola", "IDOLA", "iconoclasm feat.GUMI", "ICONOCLASMFEATGUMI", "GITADORA OverDrive", "0"],
  ["677", "Insania", "INSANIA", "Akhuta", "AKHUTA", "GITADORA OverDrive", "0"],
  ["678", "KHAMEN BREAK", "KHAMENBREAK", "くふおー", "くふおー", "GITADORA OverDrive", "0"],
  ["679", "LEMON & SALT", "LEMONSALT", "小野秀幸×96×肥塚良彦", "おのひでゆき96こえづかよしひこ", "GITADORA OverDrive", "0"],
  ["680", "LIFE", "LIFE", "Rotten Blotch", "ROTTENBLOTCH", "GITADORA OverDrive", "0"],
  ["681", "Limit Level", "LIMITLEVEL", "Sota vs 96", "SOTAVS96", "GITADORA OverDrive", "0"],
  ["682", "MODEL DD ULTIMATES", "MODELDDULTIMATES", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA OverDrive", "0"],
  ["683", "Mambo Caribbean 5", "MAMBOCARIBBEAN5", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA OverDrive", "0"],
  ["684", "NAKED SCREAM", "NAKEDSCREAM", "劇団レコードfeat.星野奏子", "げきだんれこーどFEATほしのかなこ", "GITADORA OverDrive", "0"],
  ["685", "Nature(GITADORA ver.)", "NATUREGITADORAVER", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA OverDrive", "0"],
  ["686", "Noli Me Tangere", "NOLIMETANGERE", "Akhuta", "AKHUTA", "GITADORA OverDrive", "0"],
  ["687", "Pray to the Earth", "PRAYTOTHEEARTH", "AIKO OI", "AIKOOI", "GITADORA OverDrive", "0"],
  ["688", "Quarrel and Harmony", "QUARRELANDHARMONY", "桜庭　統", "さくらばす", "GITADORA OverDrive", "0"],
  ["689", "Re:GENERATION", "REGENERATION", "TAG feat. ERi", "TAGFEATERI", "GITADORA OverDrive", "0"],
  ["690", "Silver star", "SILVERSTAR", "Trick Trap", "TRICKTRAP", "GITADORA OverDrive", "0"],
  ["691", "Summer '64", "SUMMER64", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA OverDrive", "0"],
  ["692", "TOXIC VIBRATION", "TOXICVIBRATION", "SOUND HOLIC Vs. T.Kakuta feat. YURiCa", "SOUNDHOLICVSTKAKUTAFEATYURICA", "GITADORA OverDrive", "0"],
  ["693", "The ULTIMATES -Brightness-", "THEULTIMATESBRIGHTNESS", "96", "96", "GITADORA OverDrive", "0"],
  ["694", "The ULTIMATES -Darkness-", "THEULTIMATESDARKNESS", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA OverDrive", "0"],
  ["695", "UNLIMITED FIRE", "UNLIMITEDFIRE", "TAG", "TAG", "GITADORA OverDrive", "0"],
  ["696", "War evasion", "WAREVASION", "STRAND", "STRAND", "GITADORA OverDrive", "0"],
  ["697", "heliodor", "HELIODOR", "TIME CAPSULE Lab.", "TIMECAPSULELAB", "GITADORA OverDrive", "0"],
  ["698", "jkパラダイス", "JKぱらだいす", "イオシスjkガールズ vs Pizuya's Cell", "いおしすJKがーるずVSPIZUYASCELL", "GITADORA OverDrive", "0"],
  ["699", "rage against usual", "RAGEAGAINSTUSUAL", "dj TAKA feat. Gt. Shintaro", "DJTAKAFEATGTSHINTARO", "GITADORA OverDrive", "0"],
  ["700", "あなたが思うより愛していた", "あなたがおもうよりあいしていた", "ちななん", "ちななん", "GITADORA OverDrive", "0"],
  ["701", "たまごの物理科学的 及び調理特性に関しての調査、そしてその考察", "たまごのぶつりがくてきおよびちょうりとくせいにかんしてのちょうさそしてそのこうさつ", "大日本鉄倶楽部", "だいにほんてつくらぶ", "GITADORA OverDrive", "0"],
  ["702", "だから君じゃない。", "だからきみじゃない", "AMDER WORLD feat.井上瑞巴", "AMDERWORLDFEATいのうえみずは", "GITADORA OverDrive", "0"],
  ["703", "とってもとっても、ありがとう。", "とってもとってもありがとう", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["704", "めた・メタ？ひまわり＊パンチ -デモテープVer.-", "めためたひまわりぱんちでもてーぷVER", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA OverDrive", "0"],
  ["705", "イブの時代っ！", "いぶのじだいっ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["706", "ジュピターガンズノベル", "じゅぴたーがんずのべる", "工藤吉三(ベイシスケイプ)", "くどうきちぞうべいしすけいぷ", "GITADORA OverDrive", "0"],
  ["707", "バンブーソード・ガール", "ばんぶーそーどがーる", "cosMo＠暴走P", "COSMOぼうそうP", "GITADORA OverDrive,有名楽曲", "0"],
  ["708", "ポップミュージック論", "ぽっぷんみゅーじっくろん", "ギラギラメガネ団", "ぎらぎらめがねだん", "GITADORA OverDrive", "0"],
  ["709", "一粒のナミダ", "ひとつぶのなみだ", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GITADORA OverDrive", "0"],
  ["710", "乙女繚乱 舞い咲き誇れ", "おとめりょうらんまいさきほこれ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["711", "九尾狐夜行", "きゅうびこやこう", "天狐", "てんこ", "GITADORA OverDrive", "0"],
  ["712", "今宵フラクタル", "こよいふらくたる", "純情ディスコード", "じゅんじょうでぃすこーど", "GITADORA OverDrive", "0"],
  ["713", "凛として咲く花の如く ～ひなビタ♪ edition～", "りんとしてさくはなのごとくひなびたEDITION", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["714", "凱歌の奏", "がいせんのうた", "ATSUMI UEDA", "ATSUMIUEDA", "GITADORA OverDrive", "0"],
  ["715", "天地動伝説", "てんちどうでんせつ", "98", "98", "GITADORA OverDrive", "0"],
  ["716", "守護神", "しゅごしん", "Jikki", "JIKKI", "GITADORA OverDrive,有名楽曲", "0"],
  ["717", "家出少年と迷子少女", "いえでしょうじょとまいごしょうじょ", "cosMo@暴走P", "COSMOぼうそうP", "GITADORA OverDrive,有名楽曲", "0"],
  ["718", "幻想系世界修復少女", "げんそうけいせかいしゅうふくしょうじょ", "Last Note.", "LASTNOTE", "GITADORA OverDrive,有名楽曲", "0"],
  ["719", "幽明異境", "ゆうめいいきょう", "96", "96", "GITADORA OverDrive", "0"],
  ["720", "御千手メディテーション", "おせんじゅめでぃてーしょん", "昇天家族", "しょうてんかぞく", "GITADORA OverDrive", "0"],
  ["721", "恋とキングコング", "こいときんぐこんぐ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["722", "星宿る空の下で", "ほしやどるそらのしたで", "Akhuta", "AKHUTA", "GITADORA OverDrive", "0"],
  ["723", "時雨インソムニア", "しぐれいんそむにあ", "純情ディスコード", "じゅんじょうでぃすこーど", "GITADORA OverDrive", "0"],
  ["724", "果たし状", "はたしじょう", "ATSUMI UEDA", "ATSUMIUEDA", "GITADORA OverDrive", "0"],
  ["725", "残酷な天使のテーゼ", "ざんこくなてんしのてーぜ", "", "", "GITADORA OverDrive,有名楽曲", "0"],
  ["726", "水鏡", "みかがみ", "PON", "PON", "GITADORA OverDrive", "0"],
  ["727", "温故知新でいこっ！", "おんこちしんでいこっ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["728", "滅びに至るエランプシス", "ほろびにいたるえらんぷしす", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["729", "滅亡天使 † にこきゅっぴん", "ぼくめつてんしにこきゅっぴん", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["730", "煌-灼熱の裁き-", "きらしゃくねつのさばき", "PON", "PON", "GITADORA OverDrive", "0"],
  ["731", "狂艶ノ華", "きょうえんのはな", "劇団レコードfeat.浅葉リオ", "げきだんれこーどFEATあさばりお", "GITADORA OverDrive", "0"],
  ["732", "相反オポチュニティー", "そうはんおぽちゅにてぃー", "NECOMATA MODIFY SALVATION feat.シシドヒナタ", "NECOMATAMODIFYSALVATIONFEATししどひなた", "GITADORA OverDrive", "0"],
  ["733", "童話回廊", "どうわかいろう", "DJ TOTTO", "DJTOTTO", "GITADORA OverDrive", "0"],
  ["734", "虚空と光明のディスクール", "きょくうとこうめいのでぃすくーる", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["735", "走れメロンパン", "はしれめろんぱん", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["736", "過食性:アイドル症候群", "かしょくせいあいどるしょうこうぐん", "スズム", "すずむ", "GITADORA OverDrive,有名楽曲", "0"],
  ["737", "都会征服Girls☆", "とかいせいふくGIRLS", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA OverDrive", "0"],
  ["738", "魚氷に上り 耀よひて", "うおひにのぼりかがよひて", "あさき", "あさき", "GITADORA OverDrive", "0"],
  ["740", "3 A.M. ディテクティブ・ゲーム", "3AMでぃてくてぃぶげーむ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["741", "Alternative Tactics, Second Urgent Issue", "ALTERNATIVETACTICSSECONDURGENTISSUE", "大和", "やまと", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["742", "Anathema", "ANATHEMA", "あさき", "あさき", "GITADORA Tri-Boost", "0"],
  ["743", "Arx Tyranni", "ARXTYRANNI", "Akhuta", "AKHUTA", "GITADORA Tri-Boost", "0"],
  ["744", "BELLS", "BELLS", "楽園の囚人", "らくえんのしゅうじん", "GITADORA Tri-Boost", "0"],
  ["745", "Blaze", "BLAZE", "Godspeed", "GODSPEED", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["746", "Burning Cremation", "BURNINGCREMATION", "96", "96", "GITADORA Tri-Boost", "0"],
  ["747", "Butterfly Effect", "BUTTERFLYEFFECT", "Sis Bond Chit", "SISBONDCHIT", "GITADORA Tri-Boost", "0"],
  ["748", "Covered With The Wire", "COVEREDWITHTHEWIRE", "good-cool ft. Pete Klassen", "GOODCOOLFTPETEKLASSEN", "GITADORA Tri-Boost", "0"],
  ["749", "DEMON SLAYER", "DEMONSLAYER", "96 vs. Mutsuhiko Izumi", "96VSMUTSUHIKOIZUMI", "GITADORA Tri-Boost", "0"],
  ["750", "Deep Deep Inside", "DEEPDEEPINSIDE", "ino.", "INO", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["751", "Destiny Wings", "DESTINYWINGS", "96 & keiichi", "96KEIICHI", "GITADORA Tri-Boost", "0"],
  ["752", "EMPYREAL CATASTROPHE", "EMPYREALCATASTROPHE", "山本真央樹", "やまもとまおき", "GITADORA Tri-Boost", "0"],
  ["753", "EVIL OGRE", "EVILOGRE", "TheaterR", "THEATERR", "GITADORA Tri-Boost", "0"],
  ["754", "Eisenplatte", "EISENPLATTE", "Akhuta y OJ", "AKHUTAYOJ", "GITADORA Tri-Boost", "0"],
  ["755", "FAIRY TALE", "FAIRYTALE", "colors", "COLORS", "GITADORA Tri-Boost", "0"],
  ["756", "Feed The Hunger", "FEEDTHEHUNGER", "good-cool ft. Pete Klassen", "GOODCOOLFTPETEKLASSEN", "GITADORA Tri-Boost", "0"],
  ["757", "Fire in my heart", "FIREINMYHEART", "96 & keiichi", "96KEIICHI", "GITADORA Tri-Boost", "0"],
  ["758", "Forever Young", "FOREVERYOUNG", "Rookie.F", "ROOKIEF", "GITADORA Tri-Boost", "0"],
  ["759", "GO READY", "GOREADY", "DAIHEI", "DAIHEI", "GITADORA Tri-Boost", "0"],
  ["760", "Golden galaxy", "GOLDENGALAXY", "Trick Trap", "TRICKTRAP", "GITADORA Tri-Boost", "0"],
  ["761", "Good bye, Summer～さよならは言わない～", "GOODBYESUMMERさよならはいわせない", "私立BEMANI学園軽音部 OB", "しりつBEMANIがくえんけいおんぶOB", "GITADORA Tri-Boost", "0"],
  ["762", "Graphic Melody", "GRAPHICMELODY", "山本真央樹 feat.朔白", "やまもとまおきFEATさくはく", "GITADORA Tri-Boost", "0"],
  ["763", "HAPPY！ LUCKY！ SUNFLOWER！", "HAPPYLUCKYSUNFLOWER", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA Tri-Boost", "0"],
  ["764", "In The Breeze", "INTHEBREEZE", "96 & Sota ft. Mayumi Morinaga", "96SOTAFTMAYUMIMORINAGA", "GITADORA Tri-Boost", "0"],
  ["765", "Just Believe", "JUSTBELIEVE", "小寺可南子", "こてらかなこ", "GITADORA Tri-Boost", "0"],
  ["766", "MIND ERUPTION", "MINDERUPTION", "山本真央樹", "やまもとまおき", "GITADORA Tri-Boost", "0"],
  ["767", "MODEL DD11", "MODELDD11", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost", "0"],
  ["768", "Megatonic Shaper", "MEGATONICSHAPER", "HuΣeR feat Hiromixxx", "HUΣERFEATHIROMIXXX", "GITADORA Tri-Boost", "0"],
  ["769", "My Way, My Life", "MYWAYMYLIFE", "小寺可南子", "こてらかなこ", "GITADORA Tri-Boost", "0"],
  ["770", "No Reason of Fear", "NOREASONOFFEAR", "浅田 靖", "あさだやすし", "GITADORA Tri-Boost", "0"],
  ["771", "Party People", "PARTYPEOPLE", "TAG from Party Times", "TAGFROMPARTYTIMES", "GITADORA Tri-Boost", "0"],
  ["772", "Pretty Trying", "PRETTYTRYING", "pw.a", "PWA", "GITADORA Tri-Boost", "0"],
  ["773", "RAINY DAYS", "RAINYDAYS", "colors", "COLORS", "GITADORA Tri-Boost", "0"],
  ["774", "ROZA DE ANDALUCIA", "ROZADEANDALUCIA", "SOUND HOLIC Vs. T.Kakuta feat. Nana Takahashi", "SOUNDHOLICVSTKAKUTAFEATNANATAKAHASHI", "GITADORA Tri-Boost", "0"],
  ["775", "Ruins", "RUINS", "TheaterR", "THEATERR", "GITADORA Tri-Boost", "0"],
  ["776", "Russian Caravan Rhapsody", "RUSSIANCARAVANRHAPSODY", "Power Of Nature", "POWEROFNATURE", "GITADORA Tri-Boost", "0"],
  ["777", "SEASONS", "SEASONS", "Yusuke Hiraga", "YUSUKEHIRAGA", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["778", "Sand Blow", "SANDBLOW", "肥塚良彦", "こえづかよしひこ", "GITADORA Tri-Boost", "0"],
  ["779", "Sense of the Scamper", "SENSEOFTHESCAMPER", "浅田 靖", "あさだやすし", "GITADORA Tri-Boost", "0"],
  ["780", "Skyphobia", "SKYPHOBIA", "Seku", "SEKU", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["781", "Skyscraper", "SKYSCRAPER", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost", "0"],
  ["782", "Stellar Notes", "STELLARNOTES", "setsat", "SETSAT", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["783", "Street For Student", "STREETFORSTUDENT", "good-cool", "GOODCOOL", "GITADORA Tri-Boost", "0"],
  ["784", "Surge", "SURGE", "Masahiro \"Godspeed\" Aoki", "MASAHIROGODSPEEDAOKI", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["785", "Terra Car", "TERRACAR", "Sebon", "SEBON", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["786", "The New Myth", "THENEWMYTH", "STRAND feat.Masami Okui", "STRANDFEATMASAMIOKUI", "GITADORA Tri-Boost", "0"],
  ["787", "The Town of Sunrise", "THETOWNOFSUNRISE", "DJ Genki feat. SHIN from HYPERNOVA With 三代", "DJGENKIFEATSHINFROMHYPERNOVAWITH三代", "GITADORA Tri-Boost", "0"],
  ["788", "Twilight", "TWILIGHT", "Rookie.F", "ROOKIEF", "GITADORA Tri-Boost", "0"],
  ["789", "Under The Nest -Remaster-", "UNDERTHENESTREMASTER", "Rotten Blotch", "ROTTENBLOTCH", "GITADORA Tri-Boost", "0"],
  ["790", "WITCH HUNT", "WITCHHUNT", "SOUND HOLIC feat. YURiCa", "SOUNDHOLICFEATYURICA", "GITADORA Tri-Boost", "0"],
  ["791", "double thrash", "DOUBLETHRASH", "414", "414", "GITADORA Tri-Boost", "0"],
  ["792", "neko*neko", "NEKONEKO", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["793", "wound", "WOUND", "KEENO", "KEENO", "GITADORA Tri-Boost", "0"],
  ["794", "あたしを○○してください", "あたしをしてください", "PON", "PON", "GITADORA Tri-Boost", "0"],
  ["795", "いま 我々にできること", "いまわれわれにできること", "大日本森倶楽部 feat. Koh Nishino", "だいにほんもりくらぶFEATKOHNISHINO", "GITADORA Tri-Boost", "0"],
  ["796", "とびっきりのふわっふわ", "とびっきりのふわっふわ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["797", "どきドキ バレンタイン", "どきどきばれんたいん", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA Tri-Boost", "0"],
  ["798", "はなまるぴっぴはよいこだけ", "はなまるぴっぴはよいこだけ", "A応P", "A応P", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["799", "ほおずき程度には赤い頭髪", "ほおずきていどにはあかいとうはつ", "Akhuta", "AKHUTA", "GITADORA Tri-Boost", "0"],
  ["800", "ぽかぽかレトロード", "ぽかぽかれとろーど", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["801", "めた・メタ？ひまわり＊パンチ", "めためたひまわりぱんち", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA Tri-Boost", "0"],
  ["802", "アンモノクローム", "あんものくろーむ", "DJ TOTTO", "DJTOTTO", "GITADORA Tri-Boost", "0"],
  ["803", "エキサイティング！！も・ちゃ・ちゃ☆", "えきさいてぃんぐもちゃちゃ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["804", "カケラ", "かけら", "豚乙女", "ぶたおとめ", "GITADORA Tri-Boost", "0"],
  ["805", "グッバイジョニーA", "ぐっばいじょにーA", "millll", "MILLLL", "GITADORA Tri-Boost", "0"],
  ["806", "サイレンサイン", "さいれんさいん", "元気くんバンド", "げんきくんばんど", "GITADORA Tri-Boost", "0"],
  ["807", "サヨナラ・ヘヴン -GITADOROCK ver.-", "さよならへんGITADOROCKVER", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost", "0"],
  ["808", "ジャガー人間の受難", "じゃがーにんげんのじゅなん", "工藤吉三(ベイシスケイプ)", "くどうきちぞうべいしすけいぷ", "GITADORA Tri-Boost", "0"],
  ["809", "スカイダイバー", "すかいだいばー", "ヒゲドライバー feat.ヒゲドライVAN", "ひげどらいばーFEATひげどらいVAN", "GITADORA Tri-Boost", "0"],
  ["810", "ファントムベロニカ", "ふぁんとむべろにか", "Hiromixxx", "HIROMIXXX", "GITADORA Tri-Boost", "0"],
  ["811", "フラッター現象の顛末と単一指向性の感情論", "ふらったーげんしょうのてんまつとたんいつしこうせいのかんじょうろん", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["812", "ブラックホール", "ぶらっくほーる", "達見 恵 featured by 佐野宏晃", "たつみめぐみFEATUREDBYさのひろあき", "GITADORA Tri-Boost", "0"],
  ["813", "ブランコ", "ぶらんこ", "肥塚良彦", "こえづかよしひこ", "GITADORA Tri-Boost", "0"],
  ["814", "モフモフしたいの", "もふもふしたいの", "森野くま子", "もりのくまこ", "GITADORA Tri-Boost", "0"],
  ["815", "ユグドラシルの欠片", "ゆぐどらしるのかけら", "純情ディスコード", "じゅんじょうでぃすこーど", "GITADORA Tri-Boost", "0"],
  ["816", "ラキ☆ハピDAYS!", "らきはぴDAYS", "元気くんバンド", "げんきくんばんど", "GITADORA Tri-Boost", "0"],
  ["817", "ラジカル少女", "らじかるしょうじょ", "豚乙女", "ぶたおとめ", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["818", "ララバイ哀愁", "ららばいあいしゅう", "YAMATO組－", "YAMATOぐみ", "GITADORA Tri-Boost", "0"],
  ["819", "京", "けい", "cosMo@暴走P feat.96 & 肥塚良彦", "COSMOぼうそうPFEAT96こえづかよしひこ", "GITADORA Tri-Boost", "0"],
  ["820", "六花にくちづけ", "りっかにくちづけ", "Akhuta", "AKHUTA", "GITADORA Tri-Boost", "0"],
  ["821", "在るが儘に", "あるがままに", "Des-ROW・組スペシアルr", "DESROWぐみすぺしあるR", "GITADORA Tri-Boost", "0"],
  ["822", "地方創生☆チクワクティクス", "ちほうそうせいちくわくてぃくす", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["823", "垓", "がい", "cosMo@暴走P feat.96 & 肥塚良彦", "COSMOぼうそうPFEAT96こえづかよしひこ", "GITADORA Tri-Boost", "0"],
  ["824", "夏色DIARY -GITADORA style-", "なついろDIARYGITADORASTYLE", "猫叉王子 feat.OJ", "ねこまたおうじFEATOJ", "GITADORA Tri-Boost", "0"],
  ["825", "夕星の芒野と消ゆ", "ゆうずつのすすきのときゆ", "EARTHSHAKER", "EARTHSHAKER", "GITADORA Tri-Boost", "0"],
  ["826", "天穹鳥-TEN・KYU・CHO-", "てんきゅうちょうTENKYUCHO", "劇団レコード feat.浅葉リオ", "げきだんれこーどFEATあさばりお", "GITADORA Tri-Boost", "0"],
  ["827", "太陽の子", "たいようのこ", "あさき", "あさき", "GITADORA Tri-Boost", "0"],
  ["828", "完全無欠の無重力ダイブ", "かんぜんむけつのむじゅうりょくだいぶ", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["829", "彩", "いろどり", "己龍", "きりゅう", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["830", "怒りと共に去りぬ！！", "いかりとともにさりぬ", "96 feat.すわひでお", "96FEATすわひでお", "GITADORA Tri-Boost", "0"],
  ["831", "恋する☆宇宙戦争っ！！（GITADOROCK ver.）", "こいするうちゅうせんそうっ", "Prim", "PRIM", "GITADORA Tri-Boost", "0"],
  ["832", "恋のミラクルレシピ", "こいのみらくるれしぴ", "大塚綾花", "おおつかあやか", "GITADORA Tri-Boost", "0"],
  ["833", "悠久のPEGASUS", "ゆうきゅうのPEGASUS", "SOUND HOLIC Vs. T.Kakuta feat. Nana Takahashi", "SOUNDHOLICVSTKAKUTAFEATNANATAKAHASHI", "GITADORA Tri-Boost", "0"],
  ["834", "明けぬ夜", "あけぬよる", "ユグドラシルワークスShun with 夜凪", "ゆぐどらしるわーくすSHUNWITHよなぎ", "GITADORA Tri-Boost", "0"],
  ["835", "朝顔ノ涙", "あさがおのなみだ", "龍", "りゅう", "GITADORA Tri-Boost", "0"],
  ["836", "水月鏡花のコノテーション", "すいげつきょうかのこのてーしょん", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["837", "水面静かに大地の烈日わたらせて -Remaster-", "みなもしずかにだいちのれつじるわたらせてREMASTER", "あさき", "あさき", "GITADORA Tri-Boost", "0"],
  ["838", "漆黒のスペシャルプリンセスサンデー", "しっこくのすぺしゃるぷりんせすさんでー", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["839", "激アツ☆マジヤバ☆チアガール", "げきあつまじやばちあがーる", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["840", "激情ノ華ト散ルラン", "げきじょうのはなとちるらん", "龍", "りゅう", "GITADORA Tri-Boost", "0"],
  ["841", "炎のDiargos", "ほのおのDIARGOS", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost", "0"],
  ["842", "狂鬼村正", "きょうきむらまさ", "九六VS栗須承之介", "くろくVSくりすしょうのすけ", "GITADORA Tri-Boost", "0"],
  ["843", "異常震域", "いじょうしんいき", "OSTER project", "OSTERPROJECT", "GITADORA Tri-Boost", "0"],
  ["844", "真摯撃情マイペース", "しんげきげきじょうまいぺーす", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA Tri-Boost", "0"],
  ["845", "箱庭の世界", "はこにわのせかい", "ピロカルピン", "ぴろかるぴん", "GITADORA Tri-Boost", "0"],
  ["846", "紅蓮", "ぐれん", "あさき", "あさき", "GITADORA Tri-Boost", "0"],
  ["847", "終極", "しゅうきょく", "劇団レコードfeat.浅葉リオ", "げきだんれこーどFEATあさばりお", "GITADORA Tri-Boost", "0"],
  ["848", "葬送のエウロパ", "そうそうのえうろぱ", "工藤吉三(ベイシスケイプ)", "くどうきちぞうべいしすけいぷ", "GITADORA Tri-Boost", "0"],
  ["849", "虹色遊園地", "にじいろゆうえんち", "Mutsuhiko Izumi VS DJ TOTTO", "MUTSUHIKOIZUMIVSDJTOTTO", "GITADORA Tri-Boost", "0"],
  ["850", "超獣戯画", "ちょうじゅうぎが", "96", "96", "GITADORA Tri-Boost", "0"],
  ["851", "輪廻転生", "りんねてんせい", "小林信一", "こばやししんいち", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["852", "追想 -SHINY DAYS-", "ついそうSHINYDAYS", "小寺可南子", "こてらかなこ", "GITADORA Tri-Boost", "0"],
  ["853", "透明はまだらに世界を告げて", "とうめいはまだらにせかいをつげて", "あさき×剣", "あさきけん", "GITADORA Tri-Boost", "0"],
  ["854", "遊戯大熊猫", "たわむれぱんだ", "98", "98", "GITADORA Tri-Boost", "0"],
  ["855", "鎖～KUSARI～", "くさりKUSARI", "YUA", "YUA", "GITADORA Tri-Boost", "0"],
  ["856", "零の位相", "ぜろのいそう", "kradness", "KRADNESS", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["857", "青い月", "あおいつき", "ピロカルピン", "ぴろかるぴん", "GITADORA Tri-Boost,有名楽曲", "0"],
  ["858", "黒髪乱れし修羅となりて～凛 edition～", "くろかみみだれししゅらとなりてりんEDITION", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Tri-Boost", "0"],
  ["860", "3dim", "3DIM", "PON", "PON", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["861", "And The Dead Ravened For", "ANDTHEDEADRAVENEDFOR", "Sis Bond Chit", "SISBONDCHIT", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["862", "Ater Regis -Alius-", "ATERREGISALIUS", "Akhuta", "AKHUTA", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["863", "BAD HERO", "BADHERO", "BAD HEROES", "BADHEROES", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["864", "BLACK ROSES", "BLACKROSES", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["865", "Beyond the light", "BEYONDTHELIGHT", "DAIHEI", "DAIHEI", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["866", "Blaze line", "BLAZELINE", "mitsuhiro", "MITSUHIRO", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["867", "Ding Dong Bell", "DINGDONGBELL", "A応P", "A応P", "GITADORA Tri-Boost Re:EVOLVE,有名楽曲", "0"],
  ["868", "Drastic Your Dream", "DRASTICYOURDREAM", "白澤 亮 feat. 安田みずほ", "しらさわりょうFEATやすだみずほ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["869", "Dreamer's High", "DREAMERSHIGH", "DAIHEI", "DAIHEI", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["870", "Durian", "DURIAN", "肥塚良彦", "こえづかよしひこ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["871", "Exclamation", "EXCLAMATION", "mitsuhiro", "MITSUHIRO", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["872", "Fatal Attraction", "FATALATTRACTION", "Mitsuyo", "MITSUYO", "GITADORA Tri-Boost Re:EVOLVE,有名楽曲", "0"],
  ["873", "Fly far bounce", "FLYFARBOUNCE", "猫叉Master (GITADOROCK by 泉 陸奥彦)", "ねこまたMASTERGITADOROCKBYいずみむつひこ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["874", "Hello", "HELLO", "みーちゃん", "みーちゃん", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["875", "KING G （2017Mix）", "KINGG2017MIX", "Dennis Gunn", "DENNISGUNN", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["876", "LIGHTNING", "LIGHTNING", "Anzi", "ANZI", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["877", "MEDUSA", "MEDUSA", "TheaterR", "THEATERR", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["878", "Misty Lake", "MISTYLAKE", "劇団レコード feat.浅葉リオ", "げきだんれこーどFEATあさばりお", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["879", "Monochrome Ortensia", "MONOCHROMEORTENSIA", "山本真央樹 feat.朔白", "やまもとまおきFEATさくはく", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["880", "NO MORE SORROW", "NOMORESORROW", "Rookie.F feat. Sean(from PHOENIX ASH)", "ROOKIEFFEATSEANFROMPHOENIXASH", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["881", "Our Faith (Faithful MTL Remix)", "OURFAITHFAITHFULMTLREMIX", "DOUBLE HELIX", "DOUBLEHELIX", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["882", "REFLEXES MANIPULATION", "REFLEXESMANIPULATION", "山本真央樹", "やまもとまおき", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["883", "Raspberry", "RASPBERRY", "肥塚良彦", "こえづかよしひこ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["884", "The Fourth Interval", "THEFOURTHINTERVAL", "浅田 靖", "あさだやすし", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["885", "UNDER THE SUN", "UNDERTHESUN", "colors", "COLORS", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["886", "We Go Down", "WEGODOWN", "DJ Genki feat. SHIN from HYPERNOVA With 三代", "DJGENKIFEATSHINFROMHYPERNOVAWITH三代", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["887", "White Forest", "WHITEFOREST", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["888", "†闇鍋☆ROCK†", "やみなべROCK", "ARM vs ジュクチョー feat. イオシスjkガールズ", "ARMVSじゅくちょーFEATいおしすJKがーるず", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["889", "つまり・・・Gブルース！", "つまりGぶるーす", "millll", "MILLLL", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["890", "アンタレス", "あんたれす", "ユグドラシルワークスShun with 夜凪", "ゆぐどらしるわーくすSHUNWITHよなぎ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["891", "ギタドラシカ", "ぎたどらしか", "Rookie.F feat.HIZAKI(Jupiter & Versailles)", "ROOKIEFFEATHIZAKIJUPITERVERSAILLES", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["892", "シュガーソングとビターステップ", "しゅがーそんぐとびたーすてっぷ", "", "", "GITADORA Tri-Boost Re:EVOLVE,有名楽曲", "0"],
  ["893", "タンポポ", "たんぽぽ", "豚乙女", "ぶたおとめ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["894", "主亡き機械人形のまなざし", "しゅなききかいにんぎょうのまなざし", "工藤吉三(ベイシスケイプ)", "くどうきちぞうべいしすけいぷ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["895", "傷だらけの硝子", "きずだらけのがらす", "龍", "りゅう", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["896", "刹那", "せつな", "HuΣeR feat.Fernweh", "HUΣERFEATFERNWEH", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["897", "拍子迷宮", "はくしめいきゅう", "Rookie.F", "ROOKIEF", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["898", "朧", "おぼろ", "GITADOROCK by 大和", "GITADOROCKBYやまと", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["899", "準備運動", "じゅんびうんどう", "すのうまん", "すのうまん", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["900", "瑞鳥", "みずどり", "龍", "りゅう", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["901", "背水之陣", "はいすいのじん", "すわひでお", "すわひでお", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["902", "航海 ～ Seven Colors ～", "こうかいSEVENCOLORS", "DJ TOTTO feat.Koh-ichiroh", "DJTOTTOFEATKOHICHIROH", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["903", "色ハニホヘト散リヌルヲ", "いろはにほへとちりぬるを", "小寺可南子", "こてらかなこ", "GITADORA Tri-Boost Re:EVOLVE", "0"],
  ["905", "Be a Hero!", "BEAHERO", "中島由貴", "なかじまゆき", "GITADORA Matixx", "0"],
  ["906", "CALLME", "CALLME", "Migimimi sleep tight", "MIGIMIMISLEEPTIGHT", "GITADORA Matixx", "0"],
  ["907", "DREAMING-ING!!", "DREAMINGING", "ときめきアイドル project", "ときめきあいどるPROJECT", "GITADORA Matixx", "0"],
  ["908", "Drizzly Venom", "DRIZZLYVENOM", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Matixx", "0"],
  ["909", "Fly to Sky", "FLYTOSKY", "DAIHEI", "DAIHEI", "GITADORA Matixx", "0"],
  ["910", "LIPS NOISE HUNTER", "LIPSNOISEHUNTER", "SOUND HOLIC Vs. T.Kakuta feat. Nana Takahashi", "SOUNDHOLICVSTKAKUTAFEATNANATAKAHASHI", "GITADORA Matixx", "0"],
  ["911", "Life is beautiful", "LIFEISBEAUTIFUL", "BEMANI Sound Team \"猫叉Master\"", "BEMANISOUNDTEAMねこまたMASTER", "GITADORA Matixx", "0"],
  ["912", "MONOLITH -GITADOROCK ver.-", "MONOLITHGITADOROCKVER", "TOMOSUKE feat.BEMANI Sound Team \"Mutsuhiko Izumi\"", "TOMOSUKEFEATBEMANISOUNDTEAMMUTSUHIKOIZUMI", "GITADORA Matixx", "0"],
  ["913", "Next FUTURE", "NEXTFUTURE", "SARAH", "SARAH", "GITADORA Matixx", "0"],
  ["914", "Prey", "PREY", "BEMANI Sound Team \"Dustup\"", "BEMANISOUNDTEAMDUSTUP", "GITADORA Matixx", "0"],
  ["915", "Puberty Dysthymia", "PUBERTYDYSTHYMIA", "BEMANI Sound Team \"person09\"", "BEMANISOUNDTEAMPERSON09", "GITADORA Matixx", "0"],
  ["916", "Rejoin", "REJOIN", "BEMANI Sound Team \"HuΣeR feat.PON\"", "BEMANISOUNDTEAMHUΣERFEATPON", "GITADORA Matixx", "0"],
  ["917", "SUPER SUMMER SALE", "SUPERSUMMERSALE", "BEMANI Sound Team \"U1 overground\"", "BEMANISOUNDTEAMU1OVERGROUND", "GITADORA Matixx", "0"],
  ["918", "Sacrifice", "SACRIFICE", "龍", "りゅう", "GITADORA Matixx", "0"],
  ["919", "Victoria", "VICTORIA", "HIZAKI", "HIZAKI", "GITADORA Matixx", "0"],
  ["920", "Windy Fairy -GITADOROCK ver.-", "WINDYFAIRYGITADOROCKVER", "BEMANI Sound Team \"DJ TOTTO\"", "BEMANISOUNDTEAMDJTOTTO", "GITADORA Matixx", "0"],
  ["921", "busy come, busy go!!", "BUSYCOMEBUSYGO", "Masahiro“Godspeed”Aoki", "MASAHIROGODSPEEDAOKI", "GITADORA Matixx,有名楽曲", "0"],
  ["922", "けもののおうじゃ★めうめう", "けもののおうじゃめうめう", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Matixx", "0"],
  ["923", "とびきりシュガータイム", "とびきりしゅがーたいむ", "山本真央樹 feat.朔白", "やまもとまおきFEATさくはく", "GITADORA Matixx", "0"],
  ["924", "キリステゴメン", "きりすてごめん", "東雲夏陽", "しののめなつひ", "GITADORA Matixx", "0"],
  ["925", "シノビシノノメ", "しのびしののめ", "東雲心菜", "しののめここな", "GITADORA Matixx", "0"],
  ["926", "シャルル", "しゃるる", "バルーン", "ばるーん", "GITADORA Matixx,有名楽曲", "0"],
  ["927", "チョコレートスマイル", "ちょこれーとすまいる", "日向美ビタースイーツ♪ & ここなつ", "ひなたみびたーすいーつここなつ", "GITADORA Matixx", "0"],
  ["928", "ナイト・オブ・ロンド", "ないとおぶろんど", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Matixx", "0"],
  ["929", "ビター・エスケープ", "びたーえすけーぷ", "やぎぬまかな", "やぎぬまかな", "GITADORA Matixx", "0"],
  ["930", "フリップブック＊ストーリー", "ふりっぷぶっくすとーりー", "ひまわり*パンチ", "ひまわりぱんち", "GITADORA Matixx", "0"],
  ["931", "ミカヅキ:コネクト", "みかづきこねくと", "かゆき", "かゆき", "GITADORA Matixx", "0"],
  ["932", "ミラクル・スイート・スイーツ・マジック！！", "みらくるすいーとすいーつまじっく", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Matixx", "0"],
  ["933", "レゾンデートル、前線より", "れぞんでーとるぜんせんより", "中島由貴", "なかじまゆき", "GITADORA Matixx", "0"],
  ["934", "出口入口", "でぐちいりぐち", "豚乙女", "ぶたおとめ", "GITADORA Matixx", "0"],
  ["935", "君氏危うくも近うよれ", "くんしあやうくもちこうよれ", "A応P", "A応P", "GITADORA Matixx,有名楽曲", "0"],
  ["936", "大好きなぬいぐるみ", "だいすきなぬいぐるみ", "劇団レコード feat.花柚", "げきだんれこーどFEATはなゆず", "GITADORA Matixx", "0"],
  ["937", "失恋かぞえうた", "しつれんかぞえうた", "GRAN-DRAMATIC BOYS", "GRANDRAMATICBOYS", "GITADORA Matixx", "0"],
  ["938", "幾何学的『トリックスター』", "きかがくてきとりっくすたー", "DJ Genki feat. SHIN from HYPERNOVA With 三代", "DJGENKIFEATSHINFROMHYPERNOVAWITH三代", "GITADORA Matixx", "0"],
  ["939", "星座が恋した瞬間を。", "せいざがこいしたしゅんかんを", "BEMANI Sound Team \"DJ TOTTO feat.MarL\"", "BEMANISOUNDTEAMDJTOTTOFEATMARL", "GITADORA Matixx", "0"],
  ["940", "無垢", "むく", "己龍", "きりゅう", "GITADORA Matixx,有名楽曲", "0"],
  ["941", "絶え果つ花の都より", "たえはつはなのみやこより", "Akhuta", "AKHUTA", "GITADORA Matixx", "0"],
  ["942", "銃弾は解を撃ち抜いて", "じゅうだんはかいをうちぬいて", "日向美ビタースイーツ♪", "ひなたみびたーすいーつ", "GITADORA Matixx", "0"],
  ["943", "風鈴花火", "ふうりんはなび", "BEMANI Sound Team \"劇団レコード\"feat.結良まり", "BEMANISOUNDTEAMげきだんれこーどFEATゆらまり", "GITADORA Matixx", "0"],
  ["945", "50th Memorial Songs -Beginning Story-", "50THMEMORIALSONGSBEGINNINGSTORY", "BEMANI Sound Team", "BEMANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["946", "50th Memorial Songs -Flagship medley-", "50THMEMORIALSONGSFLAGSHIPMEDLEY", "BEMANI Sound Team", "BEMANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["947", "50th Memorial Songs -The BEMANI History-", "50THMEMORIALSONGSTHEBEMANIHISTORY", "BEMANI Sound Team", "BEMANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["948", "50th Memorial Songs -二人の時 ～under the cherry blossoms～-", "50THMEMORIALSONGSふたりのときUNDERTHECHERRYBLOSSOMS", "BEMANI Sound Team", "BEMANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["949", "Afterimage d'automne", "AFTERIMAGEDAUTOMNE", "BEMANI Sound Team \"猫叉劇団\"", "BEMANISOUNDTEAMねこまたげきだん", "GITADORA EXCHAIN", "0"],
  ["950", "BLACK JACKAL (GITADORA Style)", "BLACKJACKALGITADORASTYLE", "Akira Complex with BENANI Sound Team", "AKIRACOMPLEXWITHBENANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["951", "Catch Our Fire!", "CATCHOURFIRE", "中島由貴", "なかじまゆき", "GITADORA EXCHAIN", "0"],
  ["952", "Clowing folly", "CLOWINGFOLLY", "KanadeYUK", "KANADEYUK", "GITADORA EXCHAIN", "0"],
  ["953", "DANCE of the VAMPIRE", "DANCEOFTHEVAMPIRE", "mitsuhiro", "MITSUHIRO", "GITADORA EXCHAIN", "0"],
  ["954", "FIRE 2", "FIRE2", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA EXCHAIN", "0"],
  ["955", "HANABI", "HANABI", "colors", "COLORS", "GITADORA EXCHAIN", "0"],
  ["956", "Knights Assault", "KNIGHTSASSAULT", "零 -zero-", "れいZERO", "GITADORA EXCHAIN", "0"],
  ["957", "LAS-BOS", "LASBOS", "Rookie.F feat.ダイナ四&BEMANI Sound Team \"あさき\"", "ROOKIEFFEATだいなよんBEMANISOUNDTEAMあさき", "GITADORA EXCHAIN", "0"],
  ["958", "Now or Never Mind!!!!!", "NOWORNEVERMIND", "穐田和恵 feat.MiA", "あきたかずえFEATMIA", "GITADORA EXCHAIN", "0"],
  ["959", "Road to Dream", "ROADTODREAM", "佐藤 優樹", "さとうまさき", "GITADORA EXCHAIN", "0"],
  ["960", "SESSION With You!", "SESSIONWITHYOU", "PartyCrew (from GD&pm)", "PARTYCREWFROMGDPM", "GITADORA EXCHAIN", "0"],
  ["961", "Six String Proof", "SIXSTRINGPROOF", "BEMANI Sound Team \"Yvya × Mutsuhiko Izumi\"", "BEMANISOUNDTEAMYVYAMUTSUHIKOIZUMI", "GITADORA EXCHAIN", "0"],
  ["962", "Trill auf G", "TRILLAUFG", "BEMANI Sound Team \"dj TAKA\"", "BEMANISOUNDTEAMDJTAKA", "GITADORA EXCHAIN", "0"],
  ["963", "U.N.オーエンは彼女なのか？", "UNおーえんはかのじょなのか", "岸田教団&THE明星ロケッツ", "きしだきょうだんTHEめいせいろけっつ", "GITADORA EXCHAIN,有名楽曲", "0"],
  ["964", "Ugly Duckling", "UGLYDUCKLING", "BEMANI Sound Team \"肥塚良彦\"", "BEMANISOUNDTEAMこえづかよしひこ", "GITADORA EXCHAIN", "0"],
  ["965", "might be dead", "MIGHTBEDEAD", "migimimi sleep tight", "MIGIMIMISLEEPTIGHT", "GITADORA EXCHAIN", "0"],
  ["966", "neu", "NEU", "少年ラジオ", "しょうねんらじお", "GITADORA EXCHAIN", "0"],
  ["967", "toy boxer (GITADORA Style)", "TOYBOXERGITADORASTYLE", "BEMANI Sound Team \"S-C-U & SYUNN × Yvya\"", "BEMANISOUNDTEAMSCUSYUNNYVYA", "GITADORA EXCHAIN", "0"],
  ["968", "voltississimo (GITADORA Style)", "VOLTISSISSIMOGITADORASTYLE", "BEMANI Sound Team \"PHQUASE × Yvya\"", "BEMANISOUNDTEAMPHQUASEYVYA", "GITADORA EXCHAIN", "0"],
  ["969", "××警告", "XXけいこく", "Rani", "RANI", "GITADORA EXCHAIN,有名楽曲", "0"],
  ["970", "おにぎりディスコ", "おにぎりでぃすこ", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA EXCHAIN", "0"],
  ["971", "おーまい！らぶりー！すうぃーてぃ！だーりん！", "おーまいらぶりーすうぃーてぃだーりん", "BEMANI Sound Team \"PON\" feat.NU-KO", "BEMANISOUNDTEAMPONFEATNUKO", "GITADORA EXCHAIN", "0"],
  ["972", "さんぼんがわ", "さんぼんがわ", "good-cool ft. すわひでお", "GOODCOOLFTすわひでお", "GITADORA EXCHAIN", "0"],
  ["973", "たたえよ！絶対覇権アリーシャ帝国", "たたえよぜったいはけんありーしゃていこく", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA EXCHAIN", "0"],
  ["974", "ひと夏の戯れYeah!!Samba", "ひとなつのたわむれYEAHSAMBA", "BEMANI Sound Team \"哲学\"", "BEMANISOUNDTEAM哲学", "GITADORA EXCHAIN", "0"],
  ["975", "シンクロフィッシュ", "しんくろふぃっしゅ", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA EXCHAIN", "0"],
  ["976", "ツミナガラ... と彼女は謂ふ -再-", "つみながらとかのじょはいうさい", "あさき", "あさき", "GITADORA EXCHAIN", "0"],
  ["977", "ミッドナイト☆WAR", "みっどないとWAR", "いちか", "いちか", "GITADORA EXCHAIN", "0"],
  ["978", "万物快楽理論", "ばんぶつかいらくりろん", "あさき", "あさき", "GITADORA EXCHAIN", "0"],
  ["979", "千本桜", "せんぼんざくら", "黒うさP", "くろうさP", "GITADORA EXCHAIN,有名楽曲", "0"],
  ["980", "堕羅朽", "だらく", "Des-ROW・組", "DESROWぐみ", "GITADORA EXCHAIN", "0"],
  ["981", "恋のメロディー", "こいのめろでぃー", "SARAH", "SARAH", "GITADORA EXCHAIN", "0"],
  ["982", "最小三倍完全数 (GITADORA Style)", "さいしょうさんばいかんぜんすうGITADORASTYLE", "DJ TECHNORCH with BENANI Sound Team", "DJTECHNORCHWITHBENANISOUNDTEAM", "GITADORA EXCHAIN", "0"],
  ["983", "狂髪天を撫でて綴れ雲の綻び 五体北風に散りて痕も無し", "きょうはつてんをなでてつずれぐものほころびごたいほくふうにちりてあともなし", "BEMANI Sound Team \"Akhuta Works\"", "BEMANISOUNDTEAMAKHUTAWORKS", "GITADORA EXCHAIN", "0"],
  ["984", "箱庭のエチュード", "はこにわのえちゅーど", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA EXCHAIN", "0"],
  ["985", "蛹 再", "さなぎさい", "あさき", "あさき", "GITADORA EXCHAIN", "0"],
  ["986", "言って。", "いって", "ヨルシカ", "よるしか", "GITADORA EXCHAIN,有名楽曲", "0"],
  ["987", "透明ジャスティス", "とうめいじゃすてぃす", "豚乙女", "ぶたおとめ", "GITADORA EXCHAIN", "0"],
  ["988", "霖が哭く", "りんがなく", "Power Of Nature", "POWEROFNATURE", "GITADORA EXCHAIN", "0"],
  ["990", "23 -twenty three-", "23TWENTYTHREE", "IRONBUNNY", "IRONBUNNY", "GITADORA NEX+AGE,有名楽曲", "0"],
  ["991", "Bloom Moment", "BLOOMMOMENT", "Rayflower", "RAYFLOWER", "GITADORA NEX+AGE,有名楽曲", "0"],
  ["992", "NEX＋AGE", "NEXAGE", "BEMANI Sound Team \"Yvya\"", "BEMANISOUNDTEAMYVYA", "GITADORA NEX+AGE", "0"],
  ["993", "ROOM", "ROOM", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA NEX+AGE", "0"],
  ["994", "Symphonic Tear", "SYMPHONICTEAR", "BEMANI Sound Team \"TAG\"", "BEMANISOUNDTEAMTAG", "GITADORA NEX+AGE", "0"],
  ["995", "overcome", "OVERCOME", "MEG feat. Keita", "MEGFEATKEITA", "GITADORA NEX+AGE", "0"],
  ["996", "ここからよろしく大作戦143", "ここからよろしくだいさくせん143", "BEMANI Sound Team \"あさき隊\"", "BEMANISOUNDTEAMあさきたい", "GITADORA NEX+AGE", "0"],
  ["997", "ただ君に晴れ", "ただきみにはれ", "ヨルシカ", "よるしか", "GITADORA NEX+AGE,有名楽曲", "0"],
  ["998", "イノセントバイブル", "いのせんとばいぶる", "Vanitas Lacrimosa", "VANITASLACRIMOSA", "GITADORA NEX+AGE", "0"],
  ["999", "ウソツキ横丁は雨模様", "うそつきよこちょうはあめもよう", "夜叉姫神楽", "やしゃひめかぐら", "GITADORA NEX+AGE", "0"],
  ["1000", "ソリッド", "そりっど", "豚乙女", "ぶたおとめ", "GITADORA NEX+AGE,有名楽曲", "0"],
  ["1001", "ハラショー！おにぎりサーカス団☆", "はらしょーおにぎりさーかすだん", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA NEX+AGE", "0"],
  ["1002", "プログレなぞなぞクイズのテーマ", "ぷろぐれなぞなぞくいずのてーま", "BEMANI Sound Team \"プログレッシブなぞなぞ星人\"", "BEMANISOUNDTEAMぷろぐれっしぶなぞなぞせいじん", "GITADORA NEX+AGE", "0"],
  ["1003", "ランカーキラーガール", "らんかーきらーがーる", "中島由貴 × いちか", "なかじまゆきいちか", "GITADORA NEX+AGE", "0"],
  ["1004", "叛逆のディスパレート", "はんぎゃくのでぃすぱれーど", "Vanitas Lacrimosa", "VANITASLACRIMOSA", "GITADORA NEX+AGE", "0"],
  ["1005", "天弓ノ舞", "てんきゅうのまい", "龍", "りゅう", "GITADORA NEX+AGE", "0"],
  ["1006", "宵街アテンション", "よいまちあてんしょん", "GRAN-DRAMATIC BOYS", "GRANDRAMATICBOYS", "GITADORA NEX+AGE", "0"],
  ["1007", "御伽噺に幕切れを", "おとぎりばなしにまくきれを", "夜叉姫神楽", "やしゃひめかぐら", "GITADORA NEX+AGE", "0"],
  ["1008", "至上のラトゥーリア", "しじょうのらとぅーりあ", "Vanitas Lacrimosa", "VANITASLACRIMOSA", "GITADORA NEX+AGE", "0"],
  ["1009", "超速戦士ギタドラス", "ちょうそくせんしぎたどらす", "Rookie.F feat.YOFFY(fromサイキックラバー)", "ROOKIEFFEATYOFFYFROMさいきっくらばー", "GITADORA NEX+AGE", "0"],
  ["1010", "追憶のアリア", "ついおくのありあ", "Blanc Bunny Bandit", "BLANCBUNNYBANDIT", "GITADORA NEX+AGE", "0"],
  ["1011", "逆さま シンデレラパレード", "さかさましんでれらぱれーど", "メリー・バッド・メルヘン", "めりーばっどめるへん", "GITADORA NEX+AGE", "0"],
  ["1012", "運命", "さだめ", "池田山葵", "いけだわさび", "GITADORA NEX+AGE", "0"],
  ["1013", "雷鳴", "らいめい", "SARAH(from Nine Universe) feat. 桿子 Drumstick", "SARAHFROMNINEUNIVERSEFEAT桿子DRUMSTICK", "GITADORA NEX+AGE", "0"],
  ["1015", "Accord", "ACCORD", "BEMANI Sound Team \"HuΣeR\" feat.Fernweh", "BEMANISOUNDTEAMHUΣERFEATFERNWEH", "GITADORA HIGH-VOLTAGE", "0"],
  ["1016", "Aftermath", "AFTERMATH", "BEMANI Sound Team \"猫叉Master & あさき & Yvya\"", "BEMANISOUNDTEAMねこまたMASTERあさきYVYA", "GITADORA HIGH-VOLTAGE", "0"],
  ["1017", "Bereavement", "BEREAVEMENT", "Graupel", "GRAUPEL", "GITADORA HIGH-VOLTAGE", "0"],
  ["1018", "Bonetrousle", "BONETROUSLE", "Toby Fox (Arranged by BEMANI Sound Team \"劇団レコード\")", "TOBYFOXARRANGEDBYBEMANISOUNDTEAMげきだんれこーど", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1019", "Cajuput", "CAJUPUT", "BEMANI Sound Team \"Yvya\"", "BEMANISOUNDTEAMYVYA", "GITADORA HIGH-VOLTAGE", "0"],
  ["1020", "HIGH-VOLT-AGE!!", "HIGHVOLTAGE", "仮面女子", "かめんじょし", "GITADORA HIGH-VOLTAGE", "0"],
  ["1021", "Last Goodbye / これでホントにサヨナラ", "LASTGOODBYEこれでほんとにさよなら", "Toby Fox (Arranged by BEMANI Sound Team \"Akhuta Works\")", "TOBYFOXARRANGEDBYBEMANISOUNDTEAMAKHUTAWORKS", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1022", "MEGALOVANIA", "MEGALOVANIA", "Toby Fox (Arranged by BEMANI Sound Team \"Yvya\")", "TOBYFOXARRANGEDBYBEMANISOUNDTEAMYVYA", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1023", "Never Ever End", "NEVEREVEREND", "MEG", "MEG", "GITADORA HIGH-VOLTAGE", "0"],
  ["1024", "RISE UP", "RISEUP", "Super Momo Tarosans", "SUPERMOMOTAROSANS", "GITADORA HIGH-VOLTAGE", "0"],
  ["1025", "React", "REACT", "都 啓一", "みやけいいち", "GITADORA HIGH-VOLTAGE", "0"],
  ["1026", "TAKE YOU AWAY", "TAKEYOUAWAY", "SHIN feat.MiA & BEMANI Sound Team \"あさき\"", "SHINFEATMIABEMANISOUNDTEAMあさき", "GITADORA HIGH-VOLTAGE", "0"],
  ["1027", "Triple Cross -GITADORA Edition-", "TRIPLECROSSGITADORAEDITION", "BEMANI Sound Team \"dj TAKA & DJ YOSHITAKA & SYUNN\"", "BEMANISOUNDTEAMDJTAKADJYOSHITAKASYUNN", "GITADORA HIGH-VOLTAGE", "0"],
  ["1028", "WONDER TRIP", "WONDERTRIP", "駄々子", "だだこ", "GITADORA HIGH-VOLTAGE", "0"],
  ["1029", "うっせぇわ", "うっせぇわ", "Ado", "ADO", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1030", "ひまパンケーキメイキング", "ひまぱんけーきめいきんぐ", "ひまわり＊パンチ", "ひまわりぱんち", "GITADORA HIGH-VOLTAGE", "0"],
  ["1031", "ネクロファンタジア 〜 Remix", "ねくろふぁんたじあREMIX", "Demetori", "DEMETORI", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1032", "世界の果てに約束の凱歌を", "せかいのはてにやくそくのがいせんを", "Zutt feat.NU-KO", "ZUTTFEATNUKO", "GITADORA HIGH-VOLTAGE", "0"],
  ["1033", "僕らのシンフォニア", "ぼくらのしんふぉにあ", "山本真央樹 feat.藤野マナミ", "やまもとまおきFEATふじのまなみ", "GITADORA HIGH-VOLTAGE", "0"],
  ["1034", "夜に駆ける", "よるにかける", "", "", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1035", "朱殷の手毬唄", "しゅあんのてまりうた", "犬神凶子&BEMANI Sound Team \"劇団レコード\"", "いぬがみきょうこBEMANISOUNDTEAMげきだんれこーど", "GITADORA HIGH-VOLTAGE", "0"],
  ["1036", "極普通", "ごくふつう", "おはようございます", "おはようございます", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1037", "神奏曲:ライトニング", "しんそうきょくらいとにんぐ", "神使轟く、激情の如く。", "しんしとどろくげきじょうのごとく", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1038", "終わらぬ涙の海で", "おわらぬなみだのうみで", "摩天楼オペラ", "まてんろうおぺら", "GITADORA HIGH-VOLTAGE,有名楽曲", "0"],
  ["1040", "Awakening Wings", "AWAKENINGWINGS", "伊達朱里紗", "だてありさ", "GITADORA FUZZ-UP", "0"],
  ["1041", "Beep Beep Inside", "BEEPBEEPINSIDE", "ino.", "INO", "GITADORA FUZZ-UP", "0"],
  ["1042", "Black Apple", "BLACKAPPLE", "BEMANI Sound Team \"HuΣeR\"", "BEMANISOUNDTEAMHUΣER", "GITADORA FUZZ-UP", "0"],
  ["1043", "BlackCult", "BLACKCULT", "HAGANE", "HAGANE", "GITADORA FUZZ-UP", "0"],
  ["1044", "Break Of Day", "BREAKOFDAY", "good-cool ft. Pete Klassen", "GOODCOOLFTPETEKLASSEN", "GITADORA FUZZ-UP", "0"],
  ["1045", "FOR YOUR BRAVE!!", "FORYOURBRAVE", "maro feat.藤城リエ", "MAROFEATふじしろりえ", "GITADORA FUZZ-UP", "0"],
  ["1046", "FUZZ-UP", "FUZZUP", "BEMANI Sound Team \"Yvya\"", "BEMANISOUNDTEAMYVYA", "GITADORA FUZZ-UP", "0"],
  ["1047", "GLACIER EXPRESS", "GLACIEREXPRESS", "山本真央樹", "やまもとまおき", "GITADORA FUZZ-UP", "0"],
  ["1048", "MY ENDING", "MYENDING", "あべち feat.スーパージン", "あべちFEATすーぱーじん", "GITADORA FUZZ-UP", "0"],
  ["1049", "PLAY", "PLAY", "EYE", "EYE", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1050", "Sugar Holic Candy Magic", "SUGARHOLICCANDYMAGIC", "かゆき+うぐ", "かゆきうぐ", "GITADORA FUZZ-UP", "0"],
  ["1051", "WONDER", "WONDER", "MiA feat.綾野ましろ", "MIAFEATあやのましろ", "GITADORA FUZZ-UP", "0"],
  ["1052", "グッバイ宣言", "ぐっばいせんげん", "Covered by 璃音", "COVEREDBYりおん", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1053", "テレキミ", "てれきみ", "SHIN feat.TeamMiA", "SHINFEATTEAMMIA", "GITADORA FUZZ-UP", "0"],
  ["1054", "テレキャスタービーボーイ", "てれきゃすたーびーぼーい", "すりぃ", "すりぃ", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1055", "パレットナイトフロウ", "ぱれっとないとふろう", "駄々子", "だだこ", "GITADORA FUZZ-UP", "0"],
  ["1056", "ミックスナッツ", "みっくすなっつ", "", "", "GITADORA FUZZ-UP", "0"],
  ["1057", "レジスタンス", "れじすたんす", "OSTER project feat.かなたん", "OSTERPROJECTFEATかなたん", "GITADORA FUZZ-UP", "0"],
  ["1058", "ロマンティックのかけら", "ろまんてぃっくのかけら", "AiLi", "AILI", "GITADORA FUZZ-UP", "0"],
  ["1059", "世界五分後神話", "せかいごふんごしんわ", "有形ランペイジ", "ゆうけいらんぺいじ", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1060", "我甘党", "われあまとう", "花冷え。", "はなびえ", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1061", "真っ白な闇がすべてを塗り替えても", "まっしろなやみがすべてをぬりかえても", "摩天楼オペラ", "まてんろうおぺら", "GITADORA FUZZ-UP,有名楽曲", "0"],
  ["1062", "空に触れる", "そらにふれる", "BEMANI Sound Team \"あさき\"", "BEMANISOUNDTEAMあさき", "GITADORA FUZZ-UP", "0"],
  ["1063", "血塗られたかくれんぼ", "ちぬられたかくれんぼ", "犬神凶子 & BEMANI Sound Team \"劇団レコード\"", "いぬがみきょうこBEMANISOUNDTEAMげきだんれこーど", "GITADORA FUZZ-UP", "0"],
  ["1065", "Arcadia", "ARCADIA", "Maro feat.藤城 リエ", "MAROFEATふじしろりえ", "GITADORA GALAXY WAVE", "0"],
  ["1066", "Celestial Future", "CELESTIALFUTURE", "BEMANI Sound Team \"PopStars\" feat.ＯＲＩ姫", "BEMANISOUNDTEAMPOPSTARSFEATORIひめ", "GITADORA GALAXY WAVE", "0"],
  ["1067", "HYPER JET WIND", "HYPERJETWIND", "Mutsuhiko Izumi", "MUTSUHIKOIZUMI", "GITADORA GALAXY WAVE", "0"],
  ["1068", "KING", "KING", "Covered by はるの", "COVEREDBYはるの", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1069", "WARRIOR", "WARRIOR", "NEXTRADE", "NEXTRADE", "GITADORA GALAXY WAVE", "0"],
  ["1070", "あなたしかいないから", "あなたしかいないから", "田中れいな with Team MiA", "たなかれいなWITHTEAMMIA", "GITADORA GALAXY WAVE", "0"],
  ["1071", "おこめごころ", "おこめごころ", "三矢禅晃 feat.こやまゆい", "みつやぜんこうFEATこやまゆい", "GITADORA GALAXY WAVE", "0"],
  ["1072", "さよならストローク", "さよならすとろーく", "涼平 feat. みいらみさと", "りょうへいFEATみいらみさと", "GITADORA GALAXY WAVE", "0"],
  ["1073", "アイドル", "あいどる", "BEMANI Sound Team \"HuΣeR ×wac × Yvya\" feat. 佐伯伊織", "BEMANISOUNDTEAMHUΣERWACYVYAFEATさえおきおり", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1074", "エゴロック", "えごろっく", "すりぃ", "すりぃ", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1075", "シューティンスター★☆", "しゅーてぃんすたー", "BEMANI Sound Team \"ZAQUVA\" feat. 月乃", "BEMANISOUNDTEAMZAQUVAFEATつきの", "GITADORA GALAXY WAVE", "0"],
  ["1076", "強風オールバック", "きょうふうおーるばっく", "Yukopi", "YUKOPI", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1077", "惨事のヒロイン、朝を待つ。", "さんじのひろいんあさをまつ", "駄々子", "だだこ", "GITADORA GALAXY WAVE", "0"],
  ["1078", "打打打打打打打打打打", "だだだだだだだだだだ", "ヒゲドライバー join.SELEN", "ひげどらいばーJOINSELEN", "GITADORA GALAXY WAVE", "0"],
  ["1079", "攻撃的国民的音楽", "こうげきてきこくみんてきおんがく", "八十八ヶ所巡礼", "やそはちゖしょじゅんれい", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1080", "月下美人", "げっかびじん", "石井 真之 feat.小林 正典", "いしいまさゆきFEATこばやしまさのり", "GITADORA GALAXY WAVE", "0"],
  ["1081", "爆裂パニエさん", "ばくれつぱにえさん", "tricot", "TRICOT", "GITADORA GALAXY WAVE,有名楽曲", "0"],
  ["1082", "虹の先に何があるか - Remaster -", "にじのさきになにがあるかREMASTER", "あさき", "あさき", "GITADORA GALAXY WAVE", "0"],
  ["1083", "輝石のDESTINATION feat. 花たん", "きせきのDESTINATIONFEATはなたん", "SOUND HOLIC Vs. BEMANI Sound Team \"T.Kakuta\"", "SOUNDHOLICVSBEMANISOUNDTEAMTKAKUTA", "GITADORA GALAXY WAVE", "0"],
  ["1084", "青春コンプレックス", "せいしゅんこんぷれっくす", "結束バンド", "けっそくばんど", "GITADORA GALAXY WAVE", "0"],
]
